# .github/FUNDING.yml
# This file automatically surfaces the native GitHub 'Sponsor' menu on the repository.

github: dougtrier
open_collective: trier-os
custom: ["https://www.buymeacoffee.com/dougtrier"]
