// Copyright © 2026 Trier OS. All Rights Reserved.

/**
 * © 2026 Doug Trier. All Rights Reserved.
 * Trier OS is proprietary software. Unauthorized copying,
 * distribution, or reverse engineering is strictly prohibited.
 */
/**
 * Trier OS — Database Administration API
 * =========================================
 * Administrative endpoints for database inspection, backup, restore,
 * snapshot management, and plant registration. Restricted to IT Admin
 * and authorized Backup Operator roles.
 * Mounted at /api/database in server/index.js.
 *
 * ENDPOINTS:
 *   GET    /plants                     List all registered plant databases with size and last modified
 *   PUT    /plants                     Register or update plant database metadata
 *   POST   /backup                     Trigger an immediate backup of the current plant DB
 *                                      Returns: { snapshotPath, size, checksum }
 *   GET    /export                     Download current plant DB as a SQLite binary file
 *                                      Supports: ?format=sqlite (default) | ?format=json (table dump)
 *   GET    /snapshots                  List available backup snapshots for the current plant
 *   POST   /restore                    Restore a plant DB from a named snapshot
 *                                      CAUTION: Overwrites live database — requires confirmation token
 *   GET    /privileges/backup          Check if current user has backup operator privilege
 *   POST   /privileges/backup          Grant or revoke backup operator privilege for a user
 *   POST   /import                     Import a SQLite database file into a plant slot
 *   POST   /reset-plant                Factory-reset a plant DB to the schema template
 *                                      CAUTION: Destroys all plant data — requires double confirmation
 *   GET    /privileges/import          Check if current user has import privilege
 *   POST   /privileges/import          Grant or revoke import privilege for a user
 *   POST   /cleanup-snapshots          Remove snapshots older than the retention policy (default: 30 days)
 *
 * BACKUP STRATEGY: Snapshots are SQLite hot-backup copies (WAL checkpoint + file copy).
 *   Stored in /data/backups/{plantId}/{timestamp}.db.
 *   Checksum (SHA-256) is recorded so restore integrity can be verified.
 *
 * RESTORE SAFETY: /restore requires a confirmation token generated by a prior admin action.
 *   Audit log entry is written to logistics_db before and after every restore operation.
 *
 * RESET SAFETY: /reset-plant requires two separate confirmation codes (one per request).
 *   The operation copies schema_template.db over the target plant file.
 *   Cannot be performed on the currently active plant context.
 */
const express = require('express');
const router = express.Router();
const path = require('path');
const fs = require('fs');
const db = require('../database');
const { logAudit, db: logisticsDb, isBackupAllowed } = require('../logistics_db');

const dataDir = require('../resolve_data_dir');

// Get list of available plants based on database files
router.get('/plants', (req, res) => {
    try {
        const plantsFile = path.join(dataDir, 'plants.json');
        if (!fs.existsSync(plantsFile)) {
            const defaultPlants = [
                { "id": "Anderson_IN", "label": "Anderson, IN" },
                { "id": "Battle_Creek_MI", "label": "Battle Creek, MI" },
                { "id": "Carbondale_IL", "label": "Carbondale, IL" },
                { "id": "Carlinville_IL", "label": "Carlinville, IL" },
                { "id": "Chandler_OK", "label": "Chandler, OK" },
                { "id": "Conroe_TX", "label": "Conroe, TX" },
                { "id": "Dallas_TX", "label": "Dallas, TX" },
                { "id": "Dayton_OH", "label": "Dayton, OH" },
                { "id": "Dubuque_IA", "label": "Dubuque, IA" },
                { "id": "Faribault_MN", "label": "Faribault, MN" },
                { "id": "Fort_Wayne_IN", "label": "Fort Wayne, IN" },
                { "id": "Granite_City_IL", "label": "Granite City, IL" },
                { "id": "Hammond_LA", "label": "Hammond, LA" },
                { "id": "Holland_IN", "label": "Holland, IN" },
                { "id": "Demo_Plant_1", "label": "Demo Plant 1, MO" },
                { "id": "Kansas_City_Brooklyn_MO", "label": "Kansas City, MO (Brooklyn Ave)" },
                { "id": "Kansas_City_Cleaver_MO", "label": "Kansas City, MO (Cleaver Blvd)" },
                { "id": "Kosciusko_MS", "label": "Kosciusko, MS" },
                { "id": "Little_Rock_I30_AR", "label": "Little Rock, AR (I-30)" },
                { "id": "Luana_IA", "label": "Luana, IA" },
                { "id": "Norfolk_NE", "label": "Norfolk, NE" },
                { "id": "Norman_OK", "label": "Norman, OK" },
                { "id": "OFallon_IL", "label": "O'Fallon, IL" },
                { "id": "Olney_IL", "label": "Olney, IL" },
                { "id": "Orrville_Dairy_OH", "label": "Orrville, OH (Dairy Ln)" },
                { "id": "Orrville_Vine_OH", "label": "Orrville, OH (Vine St)" },
                { "id": "Quincy_IL", "label": "Quincy, IL" },
                { "id": "Rochester_MN", "label": "Rochester, MN" },
                { "id": "Rockford_IL", "label": "Rockford, IL" },
                { "id": "Shullsburg_Miner_WI", "label": "Shullsburg, WI (Miner Way)" },
                { "id": "Shullsburg_Water_WI", "label": "Shullsburg, WI (Water St)" },
                { "id": "Sioux_Falls_SD", "label": "Sioux Falls, SD" },
                { "id": "Somerset_KY", "label": "Somerset, KY" },
                { "id": "Springfield_IL", "label": "Springfield, IL" },
                { "id": "Springfield_MO", "label": "Springfield, MO" },
                { "id": "Tyler_Fuller_TX", "label": "Tyler, TX (Fuller)" },
                { "id": "Tyler_HWY271_TX", "label": "Tyler, TX (HWY 271)" },
                { "id": "Tyler_Jacksonville_TX", "label": "Tyler, TX (Jacksonville Hwy)" },
                { "id": "Wichita_KS", "label": "Wichita, KS" },
                { "id": "Woodbury_MN", "label": "Woodbury, MN" }
            ];
            fs.writeFileSync(plantsFile, JSON.stringify(defaultPlants, null, 2));
        }

        const plants = JSON.parse(fs.readFileSync(plantsFile, 'utf8'));
        const sorted = plants.sort((a, b) => {
            if (a.id === 'Corporate_Office') return -1;
            if (b.id === 'Corporate_Office') return 1;
            
            // Check if both are generic plants
            const isPlantA = a.label.startsWith('Plant');
            const isPlantB = b.label.startsWith('Plant');
            
            if (isPlantA && isPlantB) {
                // Extract numbers
                const numA = parseInt(a.label.replace(/\D/g, ''), 10);
                const numB = parseInt(b.label.replace(/\D/g, ''), 10);
                if (!isNaN(numA) && !isNaN(numB)) {
                    return numA - numB;
                }
            }
            
            // Fallback to alphabetical
            return a.label.localeCompare(b.label);
        });

        res.json(sorted);
    } catch (err) {
        console.error('Failed to list plants:', err);
        res.status(500).json({ error: 'Failed' });
    }
});

// Save updated list of plants — auto-creates DB for new plants
router.put('/plants', (req, res) => {
    try {
        if (!req.user || (req.user.role !== 'it_admin' && req.user.globalRole !== 'it_admin' && req.user.globalRole !== 'creator')) {
            return res.status(403).json({ error: 'Administrative privileges required to modify locations.' });
        }

        const newPlants = req.body;
        if (!Array.isArray(newPlants)) {
            return res.status(400).json({ error: 'Expected an array' });
        }

        // Load existing plants to detect NEW ones
        const plantsFile = path.join(dataDir, 'plants.json');
        let existingPlants = [];
        if (fs.existsSync(plantsFile)) {
            existingPlants = JSON.parse(fs.readFileSync(plantsFile, 'utf8'));
        }
        const existingIds = new Set(existingPlants.map(p => p.id));

        // Relies exclusively on the master blueprint database so production nodes aren't linked
        const templatePath = fs.existsSync(path.join(dataDir, 'schema_template.db'))
            ? path.join(dataDir, 'schema_template.db')
            : (fs.existsSync(path.join(dataDir, 'Demo_Plant_1.db')) ? path.join(dataDir, 'Demo_Plant_1.db') : path.join(dataDir, 'schema_template.sqlite'));
            
        if (!fs.existsSync(templatePath)) {
            return res.status(500).json({ error: 'Master Schema Template DB not found. Ensure schema_template.db is in /data.' });
        }

        const created = [];
        for (const plant of newPlants) {
            if (!existingIds.has(plant.id)) {
                // New plant — create empty DB with schema from template
                const newDbPath = path.join(dataDir, `${plant.id}.db`);
                if (!fs.existsSync(newDbPath) && templatePath) {
                    try {
                        const Database = require('better-sqlite3');
                        const templateDb = new Database(templatePath, { readonly: true });

                        // Get all table creation SQL from the template
                        const tables = templateDb.prepare(
                            "SELECT sql FROM sqlite_master WHERE type='table' AND sql IS NOT NULL"
                        ).all();

                        // Get all index creation SQL
                        const indexes = templateDb.prepare(
                            "SELECT sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL"
                        ).all();

                        templateDb.close();

                        // Create the new DB and run all CREATE TABLE statements
                        const newDb = new Database(newDbPath);
                        newDb.pragma('journal_mode = WAL');

                        for (const t of tables) {
                            try {
                                newDb.exec(t.sql);
                            } catch (e) {
                                // Skip tables that conflict (e.g., sqlite_sequence)
                            }
                        }

                        // Create indexes
                        for (const idx of indexes) {
                            try {
                                newDb.exec(idx.sql);
                            } catch (e) { /* Intentional: skip conflicting indexes (e.g., sqlite_sequence) */ }
                        }

                        newDb.close();

                        // Seed initial PlantConfiguration row in logistics DB
                        try {
                            logisticsDb.prepare(`
                                INSERT OR IGNORE INTO PlantConfiguration (PlantID, ProductionModel, HubIp, UpdatedAt)
                                VALUES (?, 'fluid-process', ?, datetime('now'))
                            `).run(plant.id, plant.hubIp || null);
                        } catch (_) {}

                        created.push(plant.id);
                        console.log(`✅ Created new plant database: ${plant.id}.db (schema copied from Demo Plant 1)`);
                    } catch (dbErr) {
                        console.error(`❌ Failed to create DB for ${plant.id}:`, dbErr.message);
                    }
                }
            }
        }

        // Detect DELETED plants by diffing incoming vs existing
        const newIds = new Set(newPlants.map(p => p.id));
        const deletedPlants = existingPlants.filter(p => !newIds.has(p.id));
        
        for (const dp of deletedPlants) {
            const dpId = dp.id;
            if (dpId === 'Corporate_Office' || dpId === 'examples') {
                console.warn(`⚠️ Skipped protected location deletion request for: ${dpId}`);
                continue;
            }
            console.log(`🗑️ UI requested deletion of location: ${dpId}`);
            try {
                logisticsDb.prepare('DELETE FROM safety_incidents WHERE PlantID = ?').run(dpId);
                logisticsDb.prepare('DELETE FROM SafetyPermits WHERE PlantID = ?').run(dpId);
                logisticsDb.prepare('DELETE FROM LotoPermits WHERE PlantID = ?').run(dpId);
                logisticsDb.prepare('DELETE FROM calibration_instruments WHERE PlantID = ?').run(dpId);
                if(logisticsDb.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='compliance_inspections'").get()) {
                    logisticsDb.prepare('DELETE FROM compliance_inspections WHERE PlantID = ?').run(dpId);
                }
            } catch(e) { console.warn(`Could not wipe metadata for ${dpId}:`, e.message); }

            const dbPath = path.join(dataDir, `${dpId}.db`);
            try { if(fs.existsSync(dbPath)) fs.unlinkSync(dbPath); } catch(e) { console.warn('DB file locked; purge on reboot.'); }
            try { if(fs.existsSync(dbPath+'-wal')) fs.unlinkSync(dbPath+'-wal'); } catch(e){}
            try { if(fs.existsSync(dbPath+'-shm')) fs.unlinkSync(dbPath+'-shm'); } catch(e){}
        }

        const sorted = newPlants.sort((a, b) => a.label.localeCompare(b.label));
        fs.writeFileSync(plantsFile, JSON.stringify(sorted, null, 2));

        logAudit(req.user?.username || req.user?.Username || 'admin', 'LOCATIONS_UPDATE', 'all_sites', 
            { count: sorted.length, newDatabases: created }, 'INFO', req.ip);

        res.json({ success: true, count: sorted.length, newDatabases: created });
    } catch (err) {
        console.error('Failed to save plants:', err);
        res.status(500).json({ error: 'Failed' });
    }
});

// Delete a plant entirely
router.delete('/plants/:id', (req, res) => {
    try {
        if (!req.user || (req.user.role !== 'it_admin' && req.user.globalRole !== 'it_admin' && req.user.globalRole !== 'creator')) {
            return res.status(403).json({ error: 'Administrative privileges required.' });
        }

        const targetPlantId = req.params.id;
        if (!targetPlantId || targetPlantId === 'schema_template') {
            return res.status(400).json({ error: 'Invalid plant ID.' });
        }

        const plantsFile = path.join(dataDir, 'plants.json');
        if (fs.existsSync(plantsFile)) {
            let plants = JSON.parse(fs.readFileSync(plantsFile, 'utf8'));
            plants = plants.filter(p => p.id !== targetPlantId);
            fs.writeFileSync(plantsFile, JSON.stringify(plants, null, 2));
        }

        // Wipe global logistics aggregates
        try {
            logisticsDb.prepare('DELETE FROM safety_incidents WHERE PlantID = ?').run(targetPlantId);
            logisticsDb.prepare('DELETE FROM SafetyPermits WHERE PlantID = ?').run(targetPlantId);
            logisticsDb.prepare('DELETE FROM LotoPermits WHERE PlantID = ?').run(targetPlantId);
            logisticsDb.prepare('DELETE FROM calibration_instruments WHERE PlantID = ?').run(targetPlantId);
            // Catch if check doesn't exist
            if(logisticsDb.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='compliance_inspections'").get()) {
                logisticsDb.prepare('DELETE FROM compliance_inspections WHERE PlantID = ?').run(targetPlantId);
            }
        } catch(e) { console.warn('Could not wipe logistics metadata for deleted plant:', e.message); }

        const dbPath = path.join(dataDir, `${targetPlantId}.db`);
        try { if(fs.existsSync(dbPath)) fs.unlinkSync(dbPath); } catch(e) { console.warn('DB file locked; will purge on next reboot.'); }
        try { if(fs.existsSync(dbPath+'-wal')) fs.unlinkSync(dbPath+'-wal'); } catch(e){}
        try { if(fs.existsSync(dbPath+'-shm')) fs.unlinkSync(dbPath+'-shm'); } catch(e){}

        logAudit(req.user?.Username || 'SYSTEM', 'LOCATIONS_DELETE', targetPlantId, {}, 'CRITICAL', req.ip);

        res.json({ success: true, message: `Plant ${targetPlantId} successfully purged.` });
    } catch (err) {
        console.error('Failed to delete plant:', err);
        res.status(500).json({ error: 'Failed to delete plant' });
    }
});

// Database backup
router.post('/backup', (req, res) => {
    try {
        const activeUserRole = req.user.globalRole;
        const isCreator = req.user.globalRole === 'creator';
        const username = req.user.Username;

        const inBackupList = username ? isBackupAllowed(username) : false;

        if (activeUserRole !== 'it_admin' && !isCreator && !inBackupList) {
            return res.status(403).json({ error: 'Administrative privileges required for deep backup.' });
        }

        const plantId = db.asyncLocalStorage.getStore() || 'Demo_Plant_1';
        let dbFileName = `${plantId}.db`;
        if (plantId === 'Demo_Plant_1' && fs.existsSync(path.join(dataDir, 'Trier OS.db'))) {
            dbFileName = 'Trier OS.db';
        }

        const sourcePath = path.join(dataDir, dbFileName);
        const backupName = `${dbFileName}.bak_${Date.now()}`;
        const targetPath = path.join(dataDir, backupName);

        if (!fs.existsSync(sourcePath)) {
            return res.status(404).json({ error: 'Database not found for this location' });
        }

        // Ensure WAL is flushed before backing up
        const connection = db.getDb();
        connection.pragma('wal_checkpoint(TRUNCATE)');

        fs.copyFileSync(sourcePath, targetPath);

        logAudit(req.user?.Username || 'SYSTEM', 'DB_BACKUP', plantId, { backupName }, 'INFO', req.ip);

        res.json({ success: true, message: `Backup created: ${backupName}`, file: backupName });
    } catch (err) {
        console.error('Failed to backup:', err);
        res.status(500).json({ error: 'Backup failed' });
    }
});

// For export, we could just send the DB file
router.get('/export', (req, res) => {
    try {
        const activeUserRole = req.user.globalRole;
        const isCreator = req.user.globalRole === 'creator';
        const username = req.user.Username;

        const inBackupList = username ? isBackupAllowed(username) : false;

        if (activeUserRole !== 'it_admin' && !isCreator && !inBackupList) {
            return res.status(403).send('Forbidden: Administrative privileges required.');
        }

        const rawPlantId = req.query.plantId || db.asyncLocalStorage.getStore() || 'Demo_Plant_1';
        const plantId = req.query.plantId ? path.basename(req.query.plantId) : rawPlantId;
        let dbFileName = `${plantId}.db`;
        
        if (plantId === 'all_sites') {
            dbFileName = 'trier_logistics.db';
        } else if (plantId === 'Demo_Plant_1' && fs.existsSync(path.join(dataDir, 'Trier OS.db'))) {
            dbFileName = 'Trier OS.db';
        }

        const sourcePath = path.join(dataDir, dbFileName);

        // Boundary Check
        if (!path.resolve(sourcePath).startsWith(path.resolve(dataDir))) {
            return res.status(403).send('Boundary escape detected.');
        }

        if (!fs.existsSync(sourcePath)) {
            return res.status(404).send('Database not found');
        }

        // Ensure WAL is flushed
        const connection = db.getDb();
        connection.pragma('wal_checkpoint(TRUNCATE)');

        logAudit(req.user?.username || 'SYSTEM', 'DB_EXPORT', plantId, { dbFileName }, 'INFO', req.ip);

        res.download(sourcePath, `${plantId}_Maintenance.db`);
    } catch (err) {
        console.error('Failed to export:', err);
        res.status(500).send('Export failed');
    }
});

// List available snapshots for a plant
router.get('/snapshots', (req, res) => {
    try {
        const plantId = req.query.plantId || db.asyncLocalStorage.getStore() || 'Demo_Plant_1';
        const files = fs.readdirSync(dataDir);
        
        let dbBase = `${plantId}.db`;
        if (plantId === 'Demo_Plant_1' && fs.existsSync(path.join(dataDir, 'Trier OS.db'))) {
            dbBase = 'Trier OS.db';
        }

        const snapshots = files
            .filter(f => f.startsWith(dbBase) && (f.includes('.bak_') || f.includes('.IMPORT_SNAP_')))
            .map(f => {
                const stats = fs.statSync(path.join(dataDir, f));
                return {
                    filename: f,
                    size: stats.size,
                    created: stats.mtime
                };
            })
            .sort((a, b) => b.created - a.created);

        if (req.user.globalRole !== 'it_admin' && req.user.globalRole !== 'creator') {
            return res.status(403).json({ error: 'Access restricted to administrators.' });
        }

        res.json(snapshots);
    } catch (err) {
        res.status(500).json({ error: 'Failed to list snapshots' });
    }
});

// Restore a snapshot
router.post('/restore', (req, res) => {
    try {
        const { snapshotFile } = req.body;
        const activeUserRole = req.user.globalRole;
        const isCreator = req.user.globalRole === 'creator';

        if (activeUserRole !== 'it_admin' && !isCreator) {
            return res.status(403).json({ error: 'Administrative privileges required for database restoration.' });
        }

        if (!snapshotFile) return res.status(400).json({ error: 'No snapshot specified' });

        const safeSnapshotFile = path.basename(snapshotFile);
        const snapshotPath = path.join(dataDir, safeSnapshotFile);
        
        // Boundary Check for LFI
        if (!path.resolve(snapshotPath).startsWith(path.resolve(dataDir))) {
            return res.status(403).json({ error: 'Boundary escape detected.' });
        }

        if (!fs.existsSync(snapshotPath)) return res.status(404).json({ error: 'Snapshot not found' });

        // Determine target DB
        const plantId = db.asyncLocalStorage.getStore() || 'Demo_Plant_1';
        let dbFileName = `${plantId}.db`;
        if (plantId === 'Demo_Plant_1' && fs.existsSync(path.join(dataDir, 'Trier OS.db'))) {
            dbFileName = 'Trier OS.db';
        }
        const targetPath = path.join(dataDir, dbFileName);

        // Ensure WAL is flushed and connection is temporarily handled
        const connection = db.getDb();
        connection.pragma('wal_checkpoint(TRUNCATE)');
        
        // In a real-world high-traffic app, we should probably close connections here, 
        // but for SQLite single-file swap, copy-over usually works if WAL is flushed.
        fs.copyFileSync(snapshotPath, targetPath);

        logAudit(req.user?.username || 'it_admin', 'DB_RESTORE', plantId, { from: snapshotFile }, 'CRITICAL', req.ip);

        res.json({ success: true, message: `System restored to snapshot: ${snapshotFile}` });
    } catch (err) {
        console.error('Restore failed:', err);
        res.status(500).json({ error: 'Restore failed' });
    }
});

// Get backup privileges list
router.get('/privileges/backup', (req, res) => {
    try {
        const row = logisticsDb.prepare('SELECT Value FROM SystemSettings WHERE Key = ?').get('allowed_backup_users');
        const users = row ? JSON.parse(row.Value) : [];
        res.json(users);
    } catch (err) {
        res.json([]);
    }
});

// Update backup privileges list
router.post('/privileges/backup', (req, res) => {
    try {
        const activeUserRole = req.user.globalRole;
        const isCreator = req.user.globalRole === 'creator';
        if (activeUserRole !== 'it_admin' && !isCreator) {
            return res.status(403).json({ error: 'Only IT Admins and the Creator can manage backup privileges.' });
        }

        const { users } = req.body;
        if (!Array.isArray(users)) {
            return res.status(400).json({ error: 'Expected an array of usernames' });
        }

        logisticsDb.prepare(`
            INSERT INTO SystemSettings (Key, Value) 
            VALUES ('allowed_backup_users', ?)
            ON CONFLICT(Key) DO UPDATE SET Value = excluded.Value, UpdatedAt = CURRENT_TIMESTAMP
        `).run(JSON.stringify(users));

        logAudit(req.user?.Username || 'SYSTEM', 'PRIVILEGE_UPDATE', 'all_sites', { backupUsers: users }, 'WARNING', req.ip);

        res.json({ success: true });
    } catch (err) {
        console.error('Failed to update privileges:', err);
        res.status(500).json({ error: 'Failed to update backup privileges' });
    }
});

// Import mapped data into database
router.post('/import', (req, res) => {
    try {
        const { targetTable, data } = req.body;
        if (targetTable !== 'Asset') {
            return res.status(400).json({ error: 'Only Asset imports are currently supported' });
        }

        if (!Array.isArray(data) || data.length === 0) {
            return res.status(400).json({ error: 'Empty or invalid data payload' });
        }

        const plantId = db.asyncLocalStorage.getStore() || 'Demo_Plant_1';
        const connection = db.getDb();

        // --- AUTOMATIC SNAPSHOT BEFORE IMPORT ---
        try {
            let dbFileName = `${plantId}.db`;
            if (plantId === 'Demo_Plant_1' && fs.existsSync(path.join(dataDir, 'Trier OS.db'))) {
                dbFileName = 'Trier OS.db';
            }
            const sourcePath = path.join(dataDir, dbFileName);
            const snapshotName = `${dbFileName}.IMPORT_SNAP_${Date.now()}`;
            const targetPath = path.join(dataDir, snapshotName);

            if (fs.existsSync(sourcePath)) {
                connection.pragma('wal_checkpoint(TRUNCATE)');
                fs.copyFileSync(sourcePath, targetPath);
                console.log(`Pre-Import Snapshot created: ${snapshotName}`);
            }
        } catch (snapErr) {
            console.warn('Pre-import snapshot failed, but continuing with import:', snapErr);
        }
        // ----------------------------------------

        let inserted = 0;

        // Wrap in transaction for safety
        const insertTransaction = connection.transaction((rows) => {
            const stmt = connection.prepare(`
                INSERT OR REPLACE INTO Asset (ID, Description, Model, Manufacturer, Serial, LocationID, DeptID, Quantity, OperationalStatus, Active)
                VALUES (@AssetID, @Description, @Model, @Manufacturer, @Serial, @LocationID, @DeptID, @Quantity, @OperationalStatus, 1)
            `);

            for (const row of rows) {
                // Enterprise Schema Mapping & Sanitization
                const assetData = {
                    AssetID: row.AssetID || row.ID || 'UID-' + Math.random().toString(36).substr(2, 5).toUpperCase(),
                    Description: row.Description || row.Descript || 'Imported Asset',
                    Model: row.Model || null,
                    Manufacturer: row.Manufacturer || row.Make || row.Manufacturer || null,
                    Serial: row.Serial || null,
                    LocationID: row.LocationID || null,
                    DeptID: row.DeptID || null,
                    Quantity: parseInt(row.Quantity) || 1,
                    OperationalStatus: row.OperationalStatus || 'In Production'
                };
                stmt.run(assetData);
                inserted++;
            }
        });

        insertTransaction(data);

        logAudit(req.user?.username || 'SYSTEM', 'DB_IMPORT', db.asyncLocalStorage.getStore(), { table: targetTable, count: inserted }, 'WARNING', req.ip);

        res.json({ success: true, count: inserted });
    } catch (err) {
        console.error('Import failed:', err);
        res.status(500).json({ error: 'Failed to inject data into database' });
    }
});

// ═══════════════════════════════════════════════════════════════════════════════
// PRAIRIE DATA BRIDGE — Phase 2: Database Wipe & Reset
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Helper: Check if user has import privileges
 * Mirrors the backup privilege pattern from isBackupAllowed()
 */
function hasImportPrivilege(user) {
    if (!user) return false;
    if (user.globalRole === 'creator' || user.globalRole === 'it_admin') return true;
    // Check delegated import privilege list
    try {
        const row = logisticsDb.prepare('SELECT Value FROM SystemSettings WHERE Key = ?').get('allowed_import_users');
        if (!row) return false;
        const users = JSON.parse(row.Value);
        return Array.isArray(users) && users.includes(user.Username);
    } catch (e) {
        return false;
    }
}

/**
 * POST /api/database/reset-plant
 * 
 * Completely wipes all DATA rows from a plant database while preserving:
 * - Schema structure (all tables remain)
 * - Migration history (schema_version table)
 * - Lookup/reference tables (WorkType, WorkStatuses, Locations, Departments, 
 *   PartClasses, AssetTypes, CostCenters, Shifts, SiteLeadership, TaskTypes,
 *   PurchaseStatuses, WorkObj, ProcObj, PartObj, ObjType, Object)
 * 
 * TRIPLE-GATED SAFETY:
 *   Gate 1: Role check (Creator/IT Admin/delegated import user)
 *   Gate 2: Confirmation string (must type exact plant name)
 *   Gate 3: Mandatory pre-reset snapshot (non-skippable)
 */
router.post('/reset-plant', (req, res) => {
    try {
        // ── GATE 1: Role Check ──
        if (!hasImportPrivilege(req.user)) {
            return res.status(403).json({ 
                error: 'Import/Reset privileges required. Contact your IT Administrator.' 
            });
        }

        // ── GATE 2: Confirmation String ──
        const { confirmPlantName } = req.body;
        const plantId = db.asyncLocalStorage.getStore() || 'Demo_Plant_1';
        
        // Load plants.json to get the display label for the plant
        const plantsFile = path.join(dataDir, 'plants.json');
        let plantLabel = plantId;
        if (fs.existsSync(plantsFile)) {
            const plants = JSON.parse(fs.readFileSync(plantsFile, 'utf8'));
            const found = plants.find(p => p.id === plantId);
            if (found) plantLabel = found.label;
        }

        if (!confirmPlantName || (confirmPlantName !== plantId && confirmPlantName !== plantLabel)) {
            return res.status(400).json({ 
                error: `Safety check failed. You must type "${plantLabel}" to confirm reset.`,
                expectedConfirmation: plantLabel
            });
        }

        const connection = db.getDb();

        // ── GATE 3: Mandatory Pre-Reset Snapshot ──
        let dbFileName = `${plantId}.db`;
        if (plantId === 'Demo_Plant_1' && fs.existsSync(path.join(dataDir, 'Trier OS.db'))) {
            dbFileName = 'Trier OS.db';
        }
        const sourcePath = path.join(dataDir, dbFileName);
        const snapshotName = `${dbFileName}.RESET_SNAP_${Date.now()}`;
        const snapshotPath = path.join(dataDir, snapshotName);

        if (!fs.existsSync(sourcePath)) {
            return res.status(404).json({ error: 'Database file not found for this plant.' });
        }

        // Flush WAL and create snapshot
        connection.pragma('wal_checkpoint(TRUNCATE)');
        fs.copyFileSync(sourcePath, snapshotPath);
        console.log(`🛡️ Pre-Reset Snapshot created: ${snapshotName}`);

        // ── EXECUTE RESET ──
        // Tables to PRESERVE (lookup/reference data — no user data)
        const preserveTables = [
            'schema_version',        // Migration history
            'WorkType',              // PM, FSP, Corrective, Emergency, etc.
            'WorkStatuses',          // Open, In Progress, Complete, etc.
            'TaskTypes',             // Task type definitions
            'PurchaseStatuses',      // PO status definitions
            'AssetTypes',            // Asset category definitions
            'PartClasses',           // Part classification definitions
            'CostCenters',           // Cost center definitions
            'Shifts',                // Shift definitions
            'WorkObj', 'ProcObj', 'PartObj', 'ObjType', 'Object', // System object defs
            'zAddOn', 'zAddrCst', 'zAllComp', 'zAppInfo',         // PMC system tables
            'zCompanyVer', 'zDatabaseObjectTypePermissions',
            'zDatabaseObjectTypes', 'zDatabaseObjects',
            'zDatabaseObjectsGroups', 'zEntity', 'zErrLog',
            'zForm', 'zGroups', 'zMessage', 'zPPP', 'zPartCst',
            'zPermissionTypes', 'zPrjStat', 'zReport', 'zReqNotify',
            'zReqStatus', 'zRptcls', 'zSchType', 'zUpHist',
            'zUserCo', 'zUserGroups', 'zUserPOStat', 'zUserWOStat'
        ];

        // Tables to WIPE (all user/operational data)
        const wipeTables = [
            'Work', 'Asset', 'Part', 'Schedule', 'Vendors', 'Procedures',
            'Task', 'TaskStep',
            'WorkParts', 'WorkLabor', 'WorkNote', 'WorkMisc', 'WorkTask',
            'WorkRels', 'WorkObj',
            'PartAdjustments', 'PartVendors', 'PartLocations', 'PartOrderRules',
            'ProcedureParts', 'ProcedureTasks',
            'Locations', 'Departments', 'SiteLeadership',
            'Users', 'SystemUsers',
            'Calendar', 'Company', 'MsgCfgShare', 'MsgStd', 'Project'
        ];

        let tablesWiped = 0;
        let totalRowsDeleted = 0;

        const resetTransaction = connection.transaction(() => {
            for (const table of wipeTables) {
                try {
                    // Check if table exists before trying to delete
                    const exists = connection.prepare(
                        "SELECT name FROM sqlite_master WHERE type='table' AND name=?"
                    ).get(table);
                    
                    if (exists) {
                        const countBefore = connection.prepare(`SELECT COUNT(*) as c FROM "${table}"`).get().c;
 /* dynamic col/table - sanitize inputs */
                        if (countBefore > 0) {
                            connection.prepare(`DELETE FROM "${table}"`).run();
 /* dynamic col/table - sanitize inputs */
                            totalRowsDeleted += countBefore;
                            tablesWiped++;
                            console.log(`  🗑️ Wiped ${table}: ${countBefore} rows deleted`);
                        }
                    }
                } catch (tableErr) {
                    console.warn(`  ⚠️ Could not wipe ${table}: ${tableErr.message}`);
                }
            }
        });

        resetTransaction();

        // Log the critical event
        logAudit(
            req.user?.Username || 'SYSTEM',
            'PLANT_RESET',
            plantId,
            { 
                tablesWiped, 
                totalRowsDeleted, 
                snapshotFile: snapshotName,
                confirmedBy: req.user?.Username
            },
            'CRITICAL',
            req.ip
        );

        console.log(`\n🔴 PLANT RESET COMPLETE: ${plantId}`);
        console.log(`   Tables wiped: ${tablesWiped}`);
        console.log(`   Rows deleted: ${totalRowsDeleted}`);
        console.log(`   Snapshot: ${snapshotName}\n`);

        res.json({
            success: true,
            plant: plantId,
            plantLabel,
            tablesWiped,
            totalRowsDeleted,
            snapshotFile: snapshotName,
            message: `Plant database reset complete. ${totalRowsDeleted} rows removed from ${tablesWiped} tables. Snapshot saved as ${snapshotName}.`
        });
    } catch (err) {
        console.error('❌ Plant reset failed:', err);
        res.status(500).json({ error: 'Plant reset failed: ' });
    }
});

// ═══════════════════════════════════════════════════════════════════════════════
// Import Privilege Management (mirrors backup privilege pattern)
// ═══════════════════════════════════════════════════════════════════════════════

// Get import privileges list
router.get('/privileges/import', (req, res) => {
    try {
        const row = logisticsDb.prepare('SELECT Value FROM SystemSettings WHERE Key = ?').get('allowed_import_users');
        const users = row ? JSON.parse(row.Value) : [];
        res.json(users);
    } catch (err) {
        res.json([]);
    }
});

// Update import privileges list
router.post('/privileges/import', (req, res) => {
    try {
        if (!req.user || (req.user.globalRole !== 'it_admin' && req.user.globalRole !== 'creator')) {
            return res.status(403).json({ error: 'Only IT Admins and the Creator can manage import privileges.' });
        }

        const { users } = req.body;
        if (!Array.isArray(users)) {
            return res.status(400).json({ error: 'Expected an array of usernames' });
        }

        logisticsDb.prepare(`
            INSERT INTO SystemSettings (Key, Value) 
            VALUES ('allowed_import_users', ?)
            ON CONFLICT(Key) DO UPDATE SET Value = excluded.Value, UpdatedAt = CURRENT_TIMESTAMP
        `).run(JSON.stringify(users));

        logAudit(req.user?.Username || 'SYSTEM', 'IMPORT_PRIVILEGE_UPDATE', 'all_sites', { importUsers: users }, 'WARNING', req.ip);

        res.json({ success: true });
    } catch (err) {
        console.error('Failed to update import privileges:', err);
        res.status(500).json({ error: 'Failed to update import privileges' });
    }
});

// ═══════════════════════════════════════════════════════════════════════════════
// Snapshot Cleanup — 30 day auto-cleanup of old snapshots
// ═══════════════════════════════════════════════════════════════════════════════

router.post('/cleanup-snapshots', (req, res) => {
    try {
        if (!req.user || (req.user.globalRole !== 'it_admin' && req.user.globalRole !== 'creator')) {
            return res.status(403).json({ error: 'Administrative privileges required.' });
        }

        const THIRTY_DAYS_MS = 30 * 24 * 60 * 60 * 1000;
        const now = Date.now();
        const files = fs.readdirSync(dataDir);
        let cleaned = 0;
        const cleanedFiles = [];

        for (const file of files) {
            if (file.includes('.IMPORT_SNAP_') || file.includes('.RESET_SNAP_') || file.includes('.bak_')) {
                const filePath = path.join(dataDir, file);
                const stats = fs.statSync(filePath);
                const ageMs = now - stats.mtimeMs;

                if (ageMs > THIRTY_DAYS_MS) {
                    fs.unlinkSync(filePath);
                    cleaned++;
                    cleanedFiles.push(file);
                    console.log(`🧹 Cleaned old snapshot: ${file}`);
                }
            }
        }

        logAudit(req.user?.Username || 'SYSTEM', 'SNAPSHOT_CLEANUP', 'all_sites', { cleaned, files: cleanedFiles }, 'INFO', req.ip);

        res.json({ success: true, cleaned, files: cleanedFiles });
    } catch (err) {
        console.error('Snapshot cleanup failed:', err);
        res.status(500).json({ error: 'Cleanup failed' });
    }
});

module.exports = router;
