// Copyright © 2026 Trier OS. All Rights Reserved.

/**
 * © 2026 Doug Trier. All Rights Reserved.
 * Trier OS is proprietary software. Unauthorized copying,
 * distribution, or reverse engineering is strictly prohibited.
 */
/**
 * Trier OS — Maintenance Budget Forecaster
 * ==========================================
 * 12-month maintenance spend projection component. Visualizes the forecast
 * from the budgetForecast.js engine as bar charts with best/worst case bands.
 *
 * DISPLAY:
 *   Summary Cards   — Annual projection, monthly average, age factor, failure premium
 *   Forecast Chart  — 12-month bar chart: projected (blue), best case (green), worst case (red)
 *   Current Month   — Actual vs. projected comparison with variance % indicator
 *   Plant Breakdown — Per-plant spend ranking table (cross-plant view only)
 *
 * API: GET /api/budget-forecast
 *   Returns the full forecast payload including summary, currentMonth, forecast[],
 *   and plantBreakdown[] — all generated by the server-side forecasting engine.
 *
 * FORECAST METHODOLOGY (server-side):
 *   Weighted moving average of last 12 months actual spend
 *   × age factor (3% per year over 5 years average asset age)
 *   × failure factor (10% bump if total failures > 50)
 *   × seasonal factor (winter months weighted higher)
 *
 * @param {string} plantId - Plant identifier; 'all_sites' for enterprise aggregate
 */
import React, { useState, useEffect } from 'react';
import { BarChart2, Target, ArrowUpRight, ArrowDownRight } from 'lucide-react';
import { useTranslation } from '../i18n/index.jsx';
import LoadingSpinner from './LoadingSpinner';

export default function BudgetForecaster({ plantId }) {
    const { t } = useTranslation();
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const effectivePlant = plantId || localStorage.getItem('selectedPlantId') || 'all_sites';
        fetch('/api/analytics/budget-forecast', {
            headers: { 'x-plant-id': effectivePlant }
        })
            .then(r => r.json())
            .then(d => { setData(d); setLoading(false); })
            .catch(() => setLoading(false));
    }, [plantId]);

    if (loading) return (
        <div className="glass-card" style={{ padding: '30px', textAlign: 'center' }}>
            <BarChart2 size={24} className="spinning" color="var(--primary)" />
            <p style={{ color: 'var(--text-muted)', marginTop: '10px' }}>{t('budget.forecaster.calculatingBudgetForecast')}</p>
        </div>
    );

    if (!data || data.error) return null;

    const { summary, currentMonth, forecast, plantBreakdown } = data;
    const maxProjected = Math.max(...forecast.map(f => f.worstCase), 1);

    return (
        <div className="glass-card" style={{ padding: '25px', borderLeft: '4px solid #8b5cf6' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
                <h3 style={{ margin: 0, display: 'flex', alignItems: 'center', gap: '10px', color: '#8b5cf6' }}>
                    <Target size={22} /> {t('budget.forecaster.maintenanceBudgetForecaster')}
                </h3>
                <span style={{
                    background: 'rgba(139,92,246,0.1)', color: '#a78bfa', padding: '4px 10px',
                    borderRadius: '8px', fontSize: '0.7rem', fontWeight: 'bold'
                }}>
                    {summary.totalPlants} plant{summary.totalPlants !== 1 ? 's' : ''} • {summary.totalAssets} assets
                </span>
            </div>

            {/* Summary Cards */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '10px', marginBottom: '20px' }}>
                <div style={{ background: 'rgba(139,92,246,0.08)', padding: '15px', borderRadius: '10px', textAlign: 'center' }}>
                    <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', marginBottom: '4px' }}>12-Month History</div>
                    <div style={{ fontSize: '1.3rem', fontWeight: 'bold', color: '#a78bfa' }}>
                        ${summary.historicalSpend12m.toLocaleString()}
                    </div>
                </div>
                <div style={{ background: 'rgba(16,185,129,0.08)', padding: '15px', borderRadius: '10px', textAlign: 'center' }}>
                    <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', marginBottom: '4px' }}>{t('budget.forecaster.monthlyAvg')}</div>
                    <div style={{ fontSize: '1.3rem', fontWeight: 'bold', color: '#10b981' }}>
                        ${summary.monthlyAverage.toLocaleString()}
                    </div>
                </div>
                <div style={{ background: 'rgba(99,102,241,0.08)', padding: '15px', borderRadius: '10px', textAlign: 'center' }}>
                    <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', marginBottom: '4px' }}>{t('budget.forecaster.annualProjection')}</div>
                    <div style={{ fontSize: '1.3rem', fontWeight: 'bold', color: '#6366f1' }}>
                        ${summary.annualProjection.toLocaleString()}
                    </div>
                </div>
                <div style={{
                    background: currentMonth.variance >= 0 ? 'rgba(239,68,68,0.08)' : 'rgba(16,185,129,0.08)',
                    padding: '15px', borderRadius: '10px', textAlign: 'center'
                }}>
                    <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', marginBottom: '4px' }}>{t('budget.forecaster.currentVariance')}</div>
                    <div style={{
                        fontSize: '1.3rem', fontWeight: 'bold',
                        color: currentMonth.variance >= 0 ? '#ef4444' : '#10b981',
                        display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '4px'
                    }}>
                        {currentMonth.variance >= 0 ? <ArrowUpRight size={16} /> : <ArrowDownRight size={16} />}
                        {currentMonth.variancePercent}%
                    </div>
                </div>
            </div>

            {/* Forecast Chart — Full-Size Budget Projection */}
            <div style={{ marginBottom: '25px' }}>
                <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '15px', fontWeight: '600' }}>
                    📊 12-Month Budget Projection
                </div>

                {/* Y-Axis + Chart Area */}
                <div style={{ display: 'flex', gap: '8px' }}>
                    {/* Y-Axis Labels */}
                    <div style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between', height: '280px', paddingBottom: '24px', minWidth: '55px', textAlign: 'right' }}>
                        {[1, 0.75, 0.5, 0.25, 0].map(pct => (
                            <span key={pct} style={{ fontSize: '0.65rem', color: 'var(--text-muted)', lineHeight: '1' }}>
                                ${(maxProjected * pct / 1000).toFixed(0)}k
                            </span>
                        ))}
                    </div>

                    {/* Chart Body */}
                    <div style={{ flex: 1, position: 'relative', height: '280px' }}>
                        {/* Horizontal Gridlines */}
                        {[0, 25, 50, 75, 100].map(pct => (
                            <div key={pct} style={{
                                position: 'absolute', left: 0, right: 0,
                                bottom: `calc(${pct}% + 24px * ${1 - pct/100})`,
                                borderBottom: pct === 0 ? '1px solid rgba(255,255,255,0.15)' : '1px dashed rgba(255,255,255,0.06)',
                                zIndex: 0
                            }} />
                        ))}

                        {/* Bars Container */}
                        <div style={{ display: 'flex', gap: '6px', alignItems: 'flex-end', height: 'calc(100% - 24px)', position: 'relative', zIndex: 1 }}>
                            {forecast.map((f, i) => {
                                const date = new Date(f.month + '-01');
                                const monthLabel = date.toLocaleString('default', { month: 'short' });
                                const barPct = Math.max((f.projected / maxProjected) * 100, 2);
                                const bestPct = (f.bestCase / maxProjected) * 100;
                                const worstPct = (f.worstCase / maxProjected) * 100;
                                const isPast = date <= new Date();

                                return (
                                    <div key={f.month} style={{
                                        flex: 1, display: 'flex', flexDirection: 'column',
                                        alignItems: 'center', position: 'relative', height: '100%',
                                        justifyContent: 'flex-end',
                                    }}
                                    className="budget-bar-col"
                                    title={`${monthLabel}: $${f.projected.toLocaleString()} (Range: $${f.bestCase.toLocaleString()} – $${f.worstCase.toLocaleString()})`}
                                    >
                                        {/* Value Label */}
                                        <div style={{
                                            fontSize: '0.7rem', fontWeight: '700',
                                            color: isPast ? '#a78bfa' : '#6366f1',
                                            marginBottom: '4px', whiteSpace: 'nowrap',
                                            textShadow: '0 1px 3px rgba(0,0,0,0.5)'
                                        }}>
                                            ${(f.projected / 1000).toFixed(0)}k
                                        </div>

                                        {/* Confidence Band (worst-to-best range) */}
                                        <div style={{
                                            position: 'absolute', width: '85%',
                                            height: `${worstPct - bestPct}%`,
                                            bottom: `${bestPct}%`,
                                            background: 'rgba(139,92,246,0.12)',
                                            borderRadius: '4px', border: '1px solid rgba(139,92,246,0.15)',
                                            zIndex: 0
                                        }} />

                                        {/* Main Bar */}
                                        <div style={{
                                            width: '70%', height: `${barPct}%`, minHeight: '8px',
                                            background: isPast
                                                ? 'linear-gradient(180deg, #a78bfa 0%, #7c3aed 50%, #5b21b6 100%)'
                                                : 'linear-gradient(180deg, #6366f1 0%, #4f46e5 50%, #3730a3 100%)',
                                            borderRadius: '5px 5px 2px 2px',
                                            transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
                                            position: 'relative', zIndex: 1,
                                            boxShadow: isPast
                                                ? '0 0 12px rgba(139,92,246,0.4), inset 0 1px 0 rgba(255,255,255,0.15)'
                                                : '0 0 8px rgba(99,102,241,0.3), inset 0 1px 0 rgba(255,255,255,0.1)',
                                            cursor: 'pointer',
                                        }}
                                        className="budget-bar"
                                        />

                                        {/* Month Label */}
                                        <div style={{
                                            fontSize: '0.7rem', color: 'var(--text-muted)',
                                            marginTop: '6px', fontWeight: isPast ? '600' : '400',
                                            letterSpacing: '0.5px'
                                        }}>
                                            {monthLabel}
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                </div>

                {/* Legend */}
                <div style={{ display: 'flex', gap: '20px', marginTop: '12px', fontSize: '0.7rem', color: 'var(--text-muted)', paddingLeft: '63px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                        <div style={{ width: '12px', height: '12px', background: 'linear-gradient(180deg, #a78bfa, #5b21b6)', borderRadius: '3px' }} /> Actual / Expected
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                        <div style={{ width: '12px', height: '12px', background: 'rgba(139,92,246,0.15)', border: '1px solid rgba(139,92,246,0.3)', borderRadius: '3px' }} /> Confidence Band
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                        <span style={{ color: '#f59e0b', fontWeight: '700' }}>⚡</span> Age Factor: {summary.ageFactor}x
                    </div>
                </div>
            </div>

            <style>{`
                .budget-bar:hover {
                    transform: scaleY(1.03);
                    filter: brightness(1.2);
                    box-shadow: 0 0 20px rgba(139,92,246,0.6), inset 0 1px 0 rgba(255,255,255,0.2) !important;
                }
                .budget-bar-col:hover .budget-bar {
                    transform: scaleY(1.03);
                    filter: brightness(1.2);
                }
            `}</style>

            {/* Plant Breakdown */}
            {plantBreakdown.length > 0 && (
                <div>
                    <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '10px', fontWeight: '600' }}>
                        🏭 Plant Spend Breakdown (12mo)
                    </div>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', maxHeight: '600px', overflowY: 'auto' }}>
                        {(() => {
                            const maxSpend = Math.max(...plantBreakdown.map(pb => pb.spend12m), 1);
                            return plantBreakdown.slice(0, 15).map((pb, idx) => {
                                const pct = (pb.spend12m / maxSpend) * 100;
                                return (
                                    <div key={pb.plant} style={{
                                        position: 'relative', padding: '20px 16px',
                                        background: 'rgba(255,255,255,0.04)', borderRadius: '10px',
                                        overflow: 'visible', fontSize: '1rem',
                                        border: '1px solid rgba(255,255,255,0.06)',
                                    }}>
                                        {/* Fill bar */}
                                        <div style={{
                                            position: 'absolute', top: 0, left: 0, bottom: 0,
                                            width: `${pct}%`,
                                            background: `linear-gradient(90deg, rgba(139,92,246,${0.2 + (idx < 3 ? 0.1 : 0)}) 0%, rgba(99,102,241,0.05) 100%)`,
                                            transition: 'width 0.6s ease',
                                            borderRadius: '10px',
                                        }} />
                                        <div style={{ position: 'relative', display: 'flex', justifyContent: 'space-between', alignItems: 'center', zIndex: 1 }}>
                                            <span style={{ fontWeight: idx < 3 ? '700' : '500', color: idx < 3 ? '#e2d9f3' : '#c4b5d8', fontSize: '1rem', letterSpacing: '0.3px' }}>
                                                {idx < 3 && '🔥 '}{pb.plant.replace(/_/g, ' ')}
                                            </span>
                                            <div style={{ display: 'flex', gap: '24px', fontSize: '0.9rem', alignItems: 'center' }}>
                                                <span style={{ color: '#9ca3af' }}>{pb.woCount} WOs</span>
                                                <span style={{ color: '#9ca3af' }}>{pb.assetCount} assets</span>
                                                <span style={{
                                                    color: idx < 3 ? '#fbbf24' : '#c4b5fd',
                                                    fontWeight: 'bold', fontSize: '1.05rem', minWidth: '100px', textAlign: 'right'
                                                }}>
                                                    ${pb.spend12m.toLocaleString()}
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                );
                            });
                        })()}
                    </div>
                </div>
            )}
        </div>
    );
}
