// Copyright © 2026 Trier OS. All Rights Reserved.

/**
 * © 2026 Doug Trier. All Rights Reserved.
 * Trier OS is proprietary software. Unauthorized copying,
 * distribution, or reverse engineering is strictly prohibited.
 */
/**
 * Trier OS — Data Bridge — Database Administration Console
 * ===========================================================
 * Enterprise database management UI for IT admins and backup operators.
 * Provides direct access to database inspection and maintenance tools
 * that are too sensitive for the standard admin console.
 *
 * KEY FEATURES:
 *   Table Browser     — Browse any table in the current plant DB with column explorer
 *   Schema Viewer     — Column names, types, constraints, and indexes
 *   Export / Backup   — Download plant DB as SQLite binary or JSON table dump
 *   Snapshot Manager  — Create, list, and restore point-in-time DB snapshots
 *   Raw Data Editor   — Edit individual rows for administrative data corrections
 *                       (requires Backup Operator privilege + confirmation)
 *   Table Statistics  — Row counts and last-modified timestamps per table
 *   Danger Zone       — Factory reset and VACUUM operations (double confirmation required)
 *
 * ACCESS: Requires IT Admin role or Backup Operator privilege.
 *   Danger Zone operations additionally require a one-time confirmation token
 *   generated by the server and valid for 60 seconds only.
 *
 * API CALLS: All via /api/database/* endpoints (server/routes/database.js).
 *   All destructive operations are audit-logged to logistics_db before execution.
 */
import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { Database, Upload, Server, Globe, FolderOpen, CheckCircle, AlertTriangle, ArrowRight, ArrowLeft, FileText, Shield, ChevronRight, XCircle, Loader, ArrowUpDown, CheckSquare, Square } from 'lucide-react';
import { useTranslation } from '../i18n/index.jsx';
import { formatDate } from '../utils/formatDate';

/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * PRAIRIE DATA BRIDGE — Import Source Selector & Enterprise System Wizard
 * ═══════════════════════════════════════════════════════════════════════════════
 * 
 * Provides Enterprise System-specific and generic import wizards:
 * - PMC, Express Maintenance, MP2 dedicated connectors
 * - Generic Access (.mdb/.accdb) browser
 * - Generic SQL connection dialog
 * - Generic API connection dialog
 * 
 * All flows converge into the same staging DB → migration → production pipeline.
 */

const AUTH_HEADER = () => ({
    'Content-Type': 'application/json',
    'Authorization': `Bearer ${localStorage.getItem('authToken')}`,
    'x-plant-id': localStorage.getItem('selectedPlantId') || 'Demo_Plant_1'
});

// Enterprise System source definitions with icons and colors
const IMPORT_SOURCES = [
    { id: 'pmc',     label: 'PMC',             icon: Database, color: '#6366f1', desc: 'Trier Manufacturing Enterprise System' },
    { id: 'express', label: 'Express Maint.',   icon: Database, color: '#10b981', desc: 'Express Maintenance' },
    { id: 'mp2',     label: 'MP2',             icon: Database, color: '#f59e0b', desc: 'Infor EAM / Datastream MP2' },
    { id: 'access',  label: 'Access',          icon: FolderOpen, color: '#8b5cf6', desc: 'Any .mdb or .accdb file' },
    { id: 'sql',     label: 'SQL',             icon: Server, color: '#ef4444', desc: 'SQL Server / Express' },
    { id: 'api',     label: 'API',             icon: Globe, color: '#06b6d4', desc: 'REST API connection' }
];

export default function DataBridge({ currentPlant, userRole, onComplete }) {
    const { t } = useTranslation();
    const [activeSource, setActiveSource] = useState(null);
    const [wizardStep, setWizardStep] = useState('select'); // select, connect, browse, map, scope, confirm, importing, report
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    // File browser state
    const [legacyFiles, setLegacyFiles] = useState([]);
    const [selectedFile, setSelectedFile] = useState(null);
    const [fileSortBy, setFileSortBy] = useState('name'); // 'name', 'size', 'date'
    const [customDir, setCustomDir] = useState(''); // custom directory path to scan
    const [uploadingFile, setUploadingFile] = useState(false);
    const [dbInfo, setDbInfo] = useState(null);

    // Table browser state
    const [selectedTable, setSelectedTable] = useState(null);
    const [tableData, setTableData] = useState(null);
    const [tablePage, setTablePage] = useState(1);

    // Connector profile state
    const [connectorProfile, setConnectorProfile] = useState(null);

    // Column mapping state
    const [columnMappings, setColumnMappings] = useState({});

    // Import scope state
    const [selectedTables, setSelectedTables] = useState({});

    // Auto-match results (for generic Access imports without a connector profile)
    const [autoMatchResults, setAutoMatchResults] = useState(null);

    // SQL connection state
    const [sqlConfig, setSqlConfig] = useState({ server: '', database: '', user: '', password: '', port: '1433', encrypt: true });
    const [sqlConnected, setSqlConnected] = useState(false);

    // API connection state
    const [apiConfig, setApiConfig] = useState({ endpoint: '', apiKey: '', secret: '' });

    // Import results state
    const [importResults, setImportResults] = useState(null);

    // Confirmation
    const [confirmPlant, setConfirmPlant] = useState('');

    // Check user access
    const hasAccess = userRole === 'creator' || userRole === 'it_admin';
    if (!hasAccess) return null;

    // ═══════════════════════════════════════════════════════════════════════════
    // API CALLS
    // ═══════════════════════════════════════════════════════════════════════════

    const browseLegacyFiles = async () => {
        setLoading(true);
        try {
            const res = await fetch('/api/import/browse-legacy', { headers: AUTH_HEADER() });
            const data = await res.json();
            setLegacyFiles(data.files || []);
        } catch (err) {
            setError('Failed to browse legacy files: ' + err.message);
        }
        setLoading(false);
    };

    const openAccessFile = async (filePath) => {
        setLoading(true);
        setError(null);
        setAutoMatchResults(null);
        try {
            const res = await fetch('/api/import/open-access', {
                method: 'POST',
                headers: AUTH_HEADER(),
                body: JSON.stringify({ filePath })
            });
            const data = await res.json();
            if (res.ok) {
                setDbInfo(data);

                // Priority: 1) User-selected connector, 2) Auto-detected Enterprise System, 3) Schema auto-match
                let activeProfile = connectorProfile;

                // If no user-selected connector, check if backend fingerprinted the Enterprise System
                if (!activeProfile && data.detectedProfile) {
                    activeProfile = data.detectedProfile;
                    setConnectorProfile(data.detectedProfile);
                    console.log(`🔍 Auto-detected Enterprise System: ${data.detectedCmms} → using ${data.detectedProfile.name} connector`);
                }

                if (activeProfile) {
                    // Use connector profile to auto-select tables
                    const autoSelect = {};
                    let allFound = true;
                    Object.keys(activeProfile.tables).forEach(prairieTable => {
                        const mapping = activeProfile.tables[prairieTable];
                        const sourceTableExists = data.tables.find(t => t.name === mapping.sourceTable);
                        if (sourceTableExists) {
                            autoSelect[prairieTable] = true;
                        } else {
                            allFound = false;
                        }
                    });
                    setSelectedTables(autoSelect);

                    // If all connector tables found → skip to confirm
                    if (allFound && Object.keys(autoSelect).length > 0) {
                        setWizardStep('confirm');
                    } else {
                        setWizardStep('scope');
                    }
                } else {
                    // No connector profile and no fingerprint — run generic auto-match
                    try {
                        const matchRes = await fetch('/api/import/auto-match', {
                            method: 'POST',
                            headers: AUTH_HEADER(),
                            body: JSON.stringify({ filePath })
                        });
                        const matchData = await matchRes.json();
                        if (matchRes.ok && matchData.success) {
                            setAutoMatchResults(matchData);

                            const autoSelect = {};
                            matchData.matches.forEach(m => {
                                if (m.confidence === 'high' || m.confidence === 'medium') {
                                    autoSelect[m.sourceTable] = true;
                                }
                            });
                            setSelectedTables(autoSelect);
                            console.log(`🔍 Auto-matched ${matchData.matches.length} tables`);

                            const hasNonHighMatches = matchData.matches.some(m => m.confidence !== 'high');
                            const hasSelectedTables = Object.keys(autoSelect).length > 0;

                            if (!hasNonHighMatches && hasSelectedTables) {
                                setWizardStep('confirm');
                            } else if (hasSelectedTables) {
                                setWizardStep('scope');
                            } else {
                                setWizardStep('browse');
                            }
                        } else {
                            setWizardStep('browse');
                        }
                    } catch (matchErr) {
                        console.warn('Auto-match failed:', matchErr);
                        setWizardStep('browse');
                    }
                }
            } else {
                setError(data.error);
            }
        } catch (err) {
            setError('Failed to open database: ' + err.message);
        }
        setLoading(false);
    };

    const browseTable = async (tableName, page = 1) => {
        setLoading(true);
        try {
            let res;
            if (activeSource?.id === 'sql') {
                // SQL Server table browsing
                res = await fetch('/api/import/browse-sql-table', {
                    method: 'POST',
                    headers: AUTH_HEADER(),
                    body: JSON.stringify({ ...sqlConfig, tableName, page, limit: 50 })
                });
            } else {
                // Access file table browsing
                if (!selectedFile) { setLoading(false); return; }
                res = await fetch('/api/import/browse-access-table', {
                    method: 'POST',
                    headers: AUTH_HEADER(),
                    body: JSON.stringify({ filePath: selectedFile, tableName, page, limit: 50, oledbPassword: dbInfo?.oledbPassword })
                });
            }
            const data = await res.json();
            if (res.ok) {
                setTableData(data);
                setSelectedTable(tableName);
                setTablePage(page);
            }
        } catch (err) {
            setError('Failed to browse table');
        }
        setLoading(false);
    };

    const connectSql = async () => {
        if (!sqlConfig.server || !sqlConfig.database) {
            setError('Server and database are required');
            return;
        }
        setLoading(true);
        setError(null);
        try {
            const res = await fetch('/api/import/connect-sql', {
                method: 'POST',
                headers: AUTH_HEADER(),
                body: JSON.stringify(sqlConfig)
            });
            const data = await res.json();
            if (res.ok && data.success) {
                setSqlConnected(true);
                setDbInfo(data);
                setWizardStep('browse');
            } else {
                setError(data.error || 'Failed to connect to SQL Server');
            }
        } catch (err) {
            setError('SQL connection failed: ' + err.message);
        }
        setLoading(false);
    };

    const executeImport = async () => {
        const tablesToImport = Object.keys(selectedTables).filter(k => selectedTables[k]);
        const tablesToDefer = connectorProfile
            ? Object.keys(connectorProfile.tables).filter(k => !selectedTables[k])
            : [];

        setWizardStep('importing');
        setError(null);

        try {
            const res = await fetch('/api/import/execute', {
                method: 'POST',
                headers: AUTH_HEADER(),
                body: JSON.stringify({
                    filePath: selectedFile,
                    connectorId: connectorProfile?.id || null,
                    selectedTables: tablesToImport,
                    deferredTables: tablesToDefer,
                    oledbPassword: dbInfo?.oledbPassword
                })
            });
            const data = await res.json();
            if (res.ok && data.success) {
                setImportResults(data);
                setWizardStep('report');
            } else {
                setError(data.error || 'Import execution failed');
                setWizardStep('confirm');
            }
        } catch (err) {
            setError('Import request failed: ' + err.message);
            setWizardStep('confirm');
        }
    };

    const loadConnectorProfile = async (connectorId) => {
        try {
            const res = await fetch(`/api/import/connectors/${connectorId}`, { headers: AUTH_HEADER() });
            if (res.ok) {
                const profile = await res.json();
                setConnectorProfile(profile);
                return profile;
            }
        } catch (err) {
            console.warn('No connector profile found for', connectorId);
        }
        return null;
    };

    // ═══════════════════════════════════════════════════════════════════════════
    // SOURCE SELECTION HANDLER
    // ═══════════════════════════════════════════════════════════════════════════

    const handleSourceSelect = async (source) => {
        setActiveSource(source);
        setError(null);
        setDbInfo(null);
        setSelectedFile(null);
        setTableData(null);
        setSelectedTable(null);
        setConnectorProfile(null);
        setSelectedTables({});

        // Load connector profile if Enterprise System-specific
        if (['pmc', 'express', 'mp2'].includes(source.id)) {
            await loadConnectorProfile(source.id);
        }

        if (['pmc', 'express', 'mp2', 'access'].includes(source.id)) {
            await browseLegacyFiles();
            setWizardStep('connect');
        } else if (source.id === 'sql') {
            setWizardStep('connect');
        } else if (source.id === 'api') {
            setWizardStep('connect');
        }
    };

    const handleBack = () => {
        if (wizardStep === 'connect') {
            setActiveSource(null);
            setWizardStep('select');
        } else if (wizardStep === 'browse') {
            setWizardStep('connect');
        } else if (wizardStep === 'map') {
            setWizardStep('browse');
        } else if (wizardStep === 'scope') {
            // If we came from auto-match (skipped browse), go back to file picker
            setWizardStep('connect');
        } else if (wizardStep === 'confirm') {
            // If auto-match skipped scope, go back to scope for review; otherwise go to connect
            setWizardStep('scope');
        }
    };

    // ═══════════════════════════════════════════════════════════════════════════
    // RENDER: SOURCE SELECTOR (Step 1)
    // ═══════════════════════════════════════════════════════════════════════════

    const renderSourceSelector = () => (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '5px' }}>
                <Database size={20} color="var(--primary)" />
                <h3 style={{ margin: 0, fontSize: '1.2rem' }}>{t('data.bridge.trierDataBridge')}</h3>
                <div className="badge badge-gray" style={{ fontSize: '0.75rem', marginLeft: 'auto' }}>
                    Current Site: {currentPlant?.label}
                </div>
            </div>

            <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', margin: 0 }}>
                Select your legacy Enterprise System system to begin import, or choose a generic connector for Access, SQL, or API sources.
            </p>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '12px' }}>
                {IMPORT_SOURCES.map(source => {
                    const Icon = source.icon;
                    return (
                        <button 
                            key={source.id}
                            onClick={() => handleSourceSelect(source)}
                            style={{
                                display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
                                padding: '20px 15px', borderRadius: '14px', cursor: 'pointer',
                                background: 'rgba(255,255,255,0.03)', border: '1px solid var(--glass-border)',
                                transition: 'all 0.3s ease', gap: '10px', minHeight: '110px'
                            }}
                            onMouseEnter={e => {
                                e.currentTarget.style.borderColor = source.color;
                                e.currentTarget.style.background = `rgba(${parseInt(source.color.slice(1,3),16)},${parseInt(source.color.slice(3,5),16)},${parseInt(source.color.slice(5,7),16)},0.08)`;
                                e.currentTarget.style.transform = 'translateY(-3px)';
                                e.currentTarget.style.boxShadow = `0 8px 24px ${source.color}22`;
                            }}
                            onMouseLeave={e => {
                                e.currentTarget.style.borderColor = 'var(--glass-border)';
                                e.currentTarget.style.background = 'rgba(255,255,255,0.03)';
                                e.currentTarget.style.transform = 'translateY(0)';
                                e.currentTarget.style.boxShadow = 'none';
                            }}
                            title={`Import data from ${source.label}: ${source.desc}`}
                        >
                            <Icon size={28} color={source.color} />
                            <span style={{ fontWeight: 700, fontSize: '0.95rem', color: '#fff', fontFamily: "'Outfit', sans-serif" }}>{source.label}</span>
                            <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)', textAlign: 'center', lineHeight: '1.3' }}>{source.desc}</span>
                        </button>
                    );
                })}
            </div>
        </div>
    );

    // ═══════════════════════════════════════════════════════════════════════════
    // RENDER: FILE/CONNECTION PICKER (Step 2)
    // ═══════════════════════════════════════════════════════════════════════════

    const renderConnectionStep = () => {
        if (['pmc', 'express', 'mp2', 'access'].includes(activeSource?.id)) {
            return renderFilePicker();
        } else if (activeSource?.id === 'sql') {
            return renderSqlDialog();
        } else if (activeSource?.id === 'api') {
            return renderApiDialog();
        }
        return null;
    };

    // ── File Upload Handler ──
    const handleFileUpload = async (file) => {
        if (!file) return;
        const ext = file.name.split('.').pop().toLowerCase();
        if (ext !== 'mdb' && ext !== 'accdb') {
            setError('Only .mdb and .accdb files are supported');
            return;
        }
        setUploadingFile(true);
        setError(null);
        try {
            const formData = new FormData();
            formData.append('database', file);
            const res = await fetch('/api/import/upload-access', {
                method: 'POST',
                headers: { 'Authorization': `Bearer ${localStorage.getItem('authToken')}` },
                body: formData
            });
            const data = await res.json();
            if (res.ok && data.success) {
                // Uploaded — immediately open and auto-match
                setSelectedFile(data.file.path);
                openAccessFile(data.file.path);
            } else {
                setError(data.error || 'Upload failed');
            }
        } catch (err) {
            setError('Upload failed: ' + err.message);
        }
        setUploadingFile(false);
    };

    // ── Custom Directory Browser ──
    const browseCustomDir = async (dir) => {
        if (!dir.trim()) return;
        setLoading(true);
        setError(null);
        try {
            const res = await fetch('/api/import/browse-custom', {
                method: 'POST',
                headers: AUTH_HEADER(),
                body: JSON.stringify({ directory: dir.trim() })
            });
            const data = await res.json();
            if (res.ok) {
                setLegacyFiles(prev => {
                    // Merge with existing, avoiding duplicates by path
                    const existing = new Set(prev.map(f => f.path));
                    const newFiles = data.files.filter(f => !existing.has(f.path));
                    return [...prev, ...newFiles];
                });
                if (data.files.length === 0) {
                    setError('No .mdb or .accdb files found in that directory');
                }
            } else {
                setError(data.error || 'Failed to browse directory');
            }
        } catch (err) {
            setError('Browse failed: ' + err.message);
        }
        setLoading(false);
    };

    const renderFilePicker = () => {
        // Sort files based on selected sort criteria
        const sortedFiles = [...legacyFiles].sort((a, b) => {
            if (fileSortBy === 'size') return parseFloat(b.sizeMB) - parseFloat(a.sizeMB);
            if (fileSortBy === 'date') return new Date(b.modified) - new Date(a.modified);
            return a.name.localeCompare(b.name);
        });

        return (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                {renderWizardHeader()}

                {/* ── Drag & Drop / File Pick Zone ── */}
                <div
                    onClick={() => {
                        if (uploadingFile) return;
                        const input = document.createElement('input');
                        input.type = 'file';
                        input.accept = '.mdb,.accdb';
                        input.onchange = (e) => handleFileUpload(e.target.files[0]);
                        input.click();
                    }}
                    onDragOver={(e) => { e.preventDefault(); e.currentTarget.style.borderColor = 'var(--primary)'; e.currentTarget.style.background = 'rgba(99,102,241,0.06)'; }}
                    onDragLeave={(e) => { e.currentTarget.style.borderColor = 'var(--glass-border)'; e.currentTarget.style.background = 'rgba(0,0,0,0.15)'; }}
                    onDrop={(e) => {
                        e.preventDefault();
                        e.currentTarget.style.borderColor = 'var(--glass-border)';
                        e.currentTarget.style.background = 'rgba(0,0,0,0.15)';
                        const file = e.dataTransfer.files[0];
                        if (file) handleFileUpload(file);
                    }}
                    style={{
                        background: 'rgba(0,0,0,0.15)', padding: '30px 20px', borderRadius: '12px',
                        border: '2px dashed var(--glass-border)', textAlign: 'center',
                        cursor: uploadingFile ? 'wait' : 'pointer', transition: 'all 0.3s'
                    }}
                >
                    {uploadingFile ? (
                        <>
                            <Loader size={28} className="spinning" style={{ color: 'var(--primary)', marginBottom: '8px' }} />
                            <div style={{ fontSize: '0.9rem', fontWeight: 600 }}>Uploading & analyzing...</div>
                        </>
                    ) : (
                        <>
                            <Upload size={28} style={{ color: 'var(--primary)', marginBottom: '8px' }} />
                            <div style={{ fontSize: '0.95rem', fontWeight: 600, marginBottom: '4px' }}>Drop a database file here, or click to browse</div>
                            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>.mdb or .accdb files up to 500 MB</div>
                        </>
                    )}
                </div>

                {/* ── Custom Directory Scanner ── */}
                <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                    <FolderOpen size={16} color="var(--text-muted)" />
                    <input
                        type="text"
                        value={customDir}
                        onChange={e => setCustomDir(e.target.value)}
                        onKeyDown={e => { if (e.key === 'Enter') browseCustomDir(customDir); }}
                        placeholder={t('dataBridge.scanAFolderPathEgPlaceholder')}
                        style={{ flex: 1, padding: '8px 12px', fontSize: '0.85rem', borderRadius: '8px', border: '1px solid var(--glass-border)', background: 'rgba(0,0,0,0.15)', color: '#fff' }}
                        title={t('dataBridge.enterAFolderPathToTip')}
                    />
                    <button                         className="btn-primary"
                        onClick={() => browseCustomDir(customDir)}
                        disabled={!customDir.trim() || loading}
                        style={{ padding: '8px 16px', fontSize: '0.82rem', whiteSpace: 'nowrap' }}
                        title={t('dataBridge.scanThisFolderForMdbTip')}
                    >
                        Scan Folder
                    </button>
                </div>
                
                {/* ── File list (from legacy scan + custom scans) ── */}
                {sortedFiles.length > 0 && (
                    <div style={{ background: 'rgba(0,0,0,0.2)', padding: '15px', borderRadius: '12px', border: '1px solid var(--glass-border)' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
                            <h4 style={{ margin: 0, color: 'var(--text-muted)', fontSize: '0.85rem' }}>
                                {sortedFiles.length} database{sortedFiles.length !== 1 ? 's' : ''} found
                            </h4>
                            <div style={{ display: 'flex', gap: '4px', alignItems: 'center' }}>
                                <ArrowUpDown size={13} color="var(--text-muted)" />
                                <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)', marginRight: '4px' }}>Sort:</span>
                                {['name', 'size', 'date'].map(s => (
                                    <button 
                                        key={s}
                                        onClick={() => setFileSortBy(s)}
                                        style={{
                                            padding: '3px 10px', borderRadius: '6px', fontSize: '0.72rem', fontWeight: 600,
                                            border: '1px solid ' + (fileSortBy === s ? 'var(--primary)' : 'var(--glass-border)'),
                                            background: fileSortBy === s ? 'rgba(99,102,241,0.15)' : 'transparent',
                                            color: fileSortBy === s ? 'var(--primary)' : 'var(--text-muted)',
                                            cursor: 'pointer', textTransform: 'capitalize', transition: 'all 0.2s'
                                        }}
                                        title={`Sort files by ${s}`}
                                    >
                                        {s}
                                    </button>
                                ))}
                            </div>
                        </div>
                        <div style={{ maxHeight: '250px', overflowY: 'auto' }} className="scroll-area">
                            {sortedFiles.map((file, idx) => (
                                <div
                                    key={`item-${idx}`}
                                    onClick={() => { setSelectedFile(file.path); openAccessFile(file.path); }}
                                    style={{
                                        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                                        padding: '10px 12px', borderRadius: '8px', cursor: 'pointer',
                                        background: selectedFile === file.path ? 'rgba(99, 102, 241, 0.1)' : 'transparent',
                                        border: selectedFile === file.path ? '1px solid rgba(99, 102, 241, 0.3)' : '1px solid transparent',
                                        transition: 'all 0.2s', marginBottom: '2px'
                                    }}
                                    onMouseEnter={e => { if (selectedFile !== file.path) e.currentTarget.style.background = 'rgba(255,255,255,0.03)'; }}
                                    onMouseLeave={e => { if (selectedFile !== file.path) e.currentTarget.style.background = 'transparent'; }}
                                >
                                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                                        <FileText size={16} color="var(--primary)" />
                                        <div>
                                            <div style={{ fontWeight: 600, fontSize: '0.85rem' }}>{file.name}</div>
                                            <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>{file.path}</div>
                                        </div>
                                    </div>
                                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                                        <span className="badge badge-gray">{file.sizeMB} MB</span>
                                        <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)', minWidth: '75px', textAlign: 'right' }}>
                                            {file.modified ? formatDate(file.modified) : ''}
                                        </span>
                                        <span className="badge badge-blue">{file.format}</span>
                                        <ChevronRight size={14} color="var(--text-muted)" />
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {loading && (
                    <div style={{ textAlign: 'center', padding: '15px', color: 'var(--text-muted)' }}>
                        <Loader size={20} className="spinning" style={{ marginBottom: '6px' }} />
                        <div style={{ fontSize: '0.85rem' }}>Scanning for database files...</div>
                    </div>
                )}

                <div style={{ display: 'flex', justifyContent: 'flex-start' }}>
                    <button className="btn-secondary" onClick={handleBack} style={{ padding: '8px 16px', fontSize: '0.85rem' }} title={t('dataBridge.goBackToThePreviousTip')}>
                        <ArrowLeft size={14} /> {t('data.bridge.back')}
                    </button>
                </div>
            </div>
        );
    };

    const renderSqlDialog = () => (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
            {renderWizardHeader()}
            
            <div style={{ background: 'rgba(0,0,0,0.2)', padding: '20px', borderRadius: '12px', border: '1px solid var(--glass-border)' }}>
                <h4 style={{ margin: '0 0 15px 0', color: '#ef4444', display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <Server size={18} /> {t('data.bridge.sqlServerConnection')}
                </h4>
                
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                    {['server', 'database', 'user', 'port'].map(field => (
                        <div key={field}>
                            <label style={{ fontSize: '0.8rem', color: 'var(--text-muted)', display: 'block', marginBottom: '4px', textTransform: 'capitalize' }}>{field}</label>
                            <input
                                type="text"
                                value={sqlConfig[field]}
                                onChange={e => setSqlConfig({ ...sqlConfig, [field]: e.target.value })}
                                placeholder={field === 'server' ? 'localhost\\SQLEXPRESS' : field === 'port' ? '1433' : ''}
                                style={{ width: '100%', padding: '8px 12px' }}
                                title={`Enter the SQL Server ${field}`}
                            />
                        </div>
                    ))}
                    <div>
                        <label style={{ fontSize: '0.8rem', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>{t('data.bridge.password')}</label>
                        <input
                            type="password"
                            value={sqlConfig.password}
                            onChange={e => setSqlConfig({ ...sqlConfig, password: e.target.value })}
                            style={{ width: '100%', padding: '8px 12px' }}
                            title={t('dataBridge.enterTheSqlServerPasswordTip')}
                        />
                    </div>
                    <div style={{ display: 'flex', alignItems: 'flex-end' }}>
                        <label style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer', fontSize: '0.85rem' }}>
                            <input type="checkbox" checked={sqlConfig.encrypt} onChange={e => setSqlConfig({ ...sqlConfig, encrypt: e.target.checked })} title={t('dataBridge.enableOrDisableSslEncryptionTip')} />
                            <Shield size={14} /> {t('data.bridge.encryptConnection')}
                        </label>
                    </div>
                </div>

                <div style={{ marginTop: '15px', display: 'flex', gap: '10px', alignItems: 'center' }}>
                    <button className="btn-primary btn-sm" onClick={connectSql} disabled={loading} title={t('dataBridge.testTheConnectionToSqlTip')}>
                        {loading ? <><Loader size={14} className="spinning" /> {t('data.bridge.connecting')}</> : t('data.bridge.testConnection')}
                    </button>
                    {sqlConnected && <span style={{ color: '#10b981', display: 'flex', alignItems: 'center', gap: '5px' }}><CheckCircle size={16} /> {t('data.bridge.connected')}</span>}
                </div>
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-start' }}>
                <button className="btn-secondary" onClick={handleBack} style={{ padding: '8px 16px', fontSize: '0.85rem' }} title={t('dataBridge.goBackToThePreviousTip')}>
                    <ArrowLeft size={14} /> {t('data.bridge.back')}
                </button>
            </div>
        </div>
    );

    const renderApiDialog = () => (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
            {renderWizardHeader()}
            
            <div style={{ background: 'rgba(0,0,0,0.2)', padding: '20px', borderRadius: '12px', border: '1px solid var(--glass-border)' }}>
                <h4 style={{ margin: '0 0 15px 0', color: '#06b6d4', display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <Globe size={18} /> {t('data.bridge.apiConnection')}
                </h4>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                    <div>
                        <label style={{ fontSize: '0.8rem', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>{t('data.bridge.endpointUrl')}</label>
                        <input type="text" value={apiConfig.endpoint} onChange={e => setApiConfig({ ...apiConfig, endpoint: e.target.value })} placeholder={t('data.bridge.httpsapiexamplecomv1')} style={{ width: '100%', padding: '8px 12px' }} title={t('dataBridge.enterTheRestApiEndpointTip')} />
                    </div>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                        <div>
                            <label style={{ fontSize: '0.8rem', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>{t('data.bridge.apiKey')}</label>
                            <input type="text" value={apiConfig.apiKey} onChange={e => setApiConfig({ ...apiConfig, apiKey: e.target.value })} style={{ width: '100%', padding: '8px 12px' }} title={t('dataBridge.enterTheApiAuthenticationKeyTip')} />
                        </div>
                        <div>
                            <label style={{ fontSize: '0.8rem', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>{t('data.bridge.secret')}</label>
                            <input type="password" value={apiConfig.secret} onChange={e => setApiConfig({ ...apiConfig, secret: e.target.value })} style={{ width: '100%', padding: '8px 12px' }} title={t('dataBridge.enterTheApiSecretTip')} />
                        </div>
                    </div>

                    <button className="btn-primary btn-sm" style={{ alignSelf: 'flex-start' }} title={t('dataBridge.testTheApiConnectionTip')}>
                        {t('data.bridge.testConnection')}
                    </button>
                </div>
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-start' }}>
                <button className="btn-secondary" onClick={handleBack} style={{ padding: '8px 16px', fontSize: '0.85rem' }} title={t('dataBridge.goBackToThePreviousTip')}>
                    <ArrowLeft size={14} /> {t('data.bridge.back')}
                </button>
            </div>
        </div>
    );

    // ═══════════════════════════════════════════════════════════════════════════
    // RENDER: TABLE BROWSER (Step 3)
    // ═══════════════════════════════════════════════════════════════════════════

    const renderTableBrowser = () => (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
            {renderWizardHeader()}

            <div style={{ display: 'grid', gridTemplateColumns: '280px 1fr', gap: '15px', minHeight: '400px' }}>
                {/* Table list sidebar */}
                <div style={{ background: 'rgba(0,0,0,0.2)', padding: '15px', borderRadius: '12px', border: '1px solid var(--glass-border)', overflowY: 'auto' }} className="scroll-area">
                    <h4 style={{ margin: '0 0 12px 0', color: 'var(--primary)', fontSize: '0.9rem' }}>
                        Tables ({dbInfo?.tables?.length || 0})
                    </h4>
                    {dbInfo?.tables?.map((table, idx) => {
                        // Check if this table has a connector profile mapping
                        const profileMatch = connectorProfile ? 
                            Object.entries(connectorProfile.tables).find(([_, cfg]) => cfg.sourceTable === table.name) : null;

                        return (
                            <div
                                key={`item-${idx}`}
                                onClick={() => browseTable(table.name)}
                                style={{
                                    padding: '8px 10px', borderRadius: '6px', cursor: 'pointer',
                                    background: selectedTable === table.name ? 'rgba(99, 102, 241, 0.15)' : 'transparent',
                                    border: selectedTable === table.name ? '1px solid rgba(99, 102, 241, 0.3)' : '1px solid transparent',
                                    transition: 'all 0.15s', marginBottom: '2px',
                                    display: 'flex', justifyContent: 'space-between', alignItems: 'center'
                                }}
                                onMouseEnter={e => { if (selectedTable !== table.name) e.currentTarget.style.background = 'rgba(255,255,255,0.03)'; }}
                                onMouseLeave={e => { if (selectedTable !== table.name) e.currentTarget.style.background = selectedTable === table.name ? 'rgba(99, 102, 241, 0.15)' : 'transparent'; }}
                            >
                                <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                                    {profileMatch && <div style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#10b981' }} />}
                                    <span style={{ fontSize: '0.82rem', fontWeight: selectedTable === table.name ? 600 : 400 }}>{table.name}</span>
                                </div>
                                <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>{table.columnCount} cols</span>
                            </div>
                        );
                    })}
                </div>

                {/* Table data view */}
                <div style={{ background: 'rgba(0,0,0,0.15)', padding: '15px', borderRadius: '12px', border: '1px solid var(--glass-border)', overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
                    {!tableData ? (
                        <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-muted)' }}>
                            <p>{t('data.bridge.clickATableTo')}</p>
                        </div>
                    ) : loading ? (
                        <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                            <Loader size={24} className="spinning" />
                        </div>
                    ) : (
                        <>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
                                <h4 style={{ margin: 0, fontSize: '0.9rem' }}>
                                    {tableData.tableName}
                                    <span style={{ color: 'var(--text-muted)', fontWeight: 400, marginLeft: '8px', fontSize: '0.8rem' }}>
                                        {tableData.totalRows} rows
                                    </span>
                                </h4>
                                {tableData.totalPages > 1 && (
                                    <div style={{ display: 'flex', gap: '5px', alignItems: 'center', fontSize: '0.8rem' }}>
                                        <button className="btn-secondary" onClick={() => browseTable(tableData.tableName, tablePage - 1)} disabled={tablePage <= 1} style={{ padding: '4px 8px', fontSize: '0.75rem' }} title={t('dataBridge.previousPageTip')}>←</button>
                                        <span style={{ color: 'var(--text-muted)' }}>Page {tablePage} of {tableData.totalPages}</span>
                                        <button className="btn-secondary" onClick={() => browseTable(tableData.tableName, tablePage + 1)} disabled={tablePage >= tableData.totalPages} style={{ padding: '4px 8px', fontSize: '0.75rem' }} title={t('dataBridge.nextPageTip')}>→</button>
                                    </div>
                                )}
                            </div>
                            <div style={{ flex: 1, overflowX: 'auto', overflowY: 'auto' }} className="scroll-area">
                                <table className="data-table" style={{ fontSize: '0.78rem' }}>
                                    <thead>
                                        <tr>
                                            {tableData.columns?.slice(0, 10).map(col => (
                                                <th key={col} style={{ whiteSpace: 'nowrap', padding: '6px 10px' }}>{col}</th>
                                            ))}
                                            {tableData.columns?.length > 10 && <th style={{ padding: '6px' }}>+{tableData.columns.length - 10} more</th>}
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {tableData.data?.map((row, idx) => (
                                            <tr key={`item-${idx}`}>
                                                {tableData.columns?.slice(0, 10).map(col => (
                                                    <td key={col} style={{ padding: '6px 10px', maxWidth: '200px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                                                        {row[col] != null ? String(row[col]) : <span style={{ opacity: 0.3 }}>—</span>}
                                                    </td>
                                                ))}
                                                {tableData.columns?.length > 10 && <td style={{ opacity: 0.3 }}>…</td>}
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </>
                    )}
                </div>
            </div>

            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <button className="btn-secondary" onClick={handleBack} style={{ padding: '8px 16px', fontSize: '0.85rem' }} title={t('dataBridge.goBackToThePreviousTip')}>
                    <ArrowLeft size={14} /> {t('data.bridge.back')}
                </button>
                <button className="btn-primary btn-sm" onClick={() => setWizardStep('scope')} title={t('dataBridge.continueToConfigureImportScopeTip')}>
                    {t('data.bridge.configureImport')} <ArrowRight size={14} />
                </button>
            </div>
        </div>
    );

    // ═══════════════════════════════════════════════════════════════════════════
    // RENDER: IMPORT SCOPE (Step 4 — Table Selection with Checkboxes)
    // ═══════════════════════════════════════════════════════════════════════════

    const renderScopeSelector = () => {
        // Build list of importable tables
        let importableTables;

        if (connectorProfile) {
            // Use connector profile mappings
            importableTables = Object.entries(connectorProfile.tables).map(([prairieTable, cfg]) => {
                const sourceMatch = dbInfo?.tables?.find(t => t.name === cfg.sourceTable);
                return {
                    prairieTable,
                    sourceTable: cfg.sourceTable,
                    found: !!sourceMatch,
                    columnCount: sourceMatch?.columnCount || 0,
                    mappedColumns: Object.keys(cfg.columns).length,
                    confidence: sourceMatch ? 'high' : 'none',
                    rowCount: 0
                };
            });
        } else if (autoMatchResults?.matches?.length > 0) {
            // Use auto-match results — show matched tables first, then unmatched
            const matchedTables = autoMatchResults.matches.map(m => ({
                prairieTable: m.sourceTable,  // Use source table name as the key for import
                sourceTable: m.sourceTable,
                targetTable: m.prairieTable,
                found: true,
                columnCount: m.totalSourceColumns,
                mappedColumns: m.matchedColumns,
                confidence: m.confidence,
                score: m.score,
                rowCount: m.sourceRowCount
            }));

            // Add unmatched source tables
            const unmatchedTables = (autoMatchResults.unmatchedSource || []).map(name => {
                const tbl = dbInfo?.tables?.find(t => t.name === name);
                return {
                    prairieTable: name,
                    sourceTable: name,
                    targetTable: null,
                    found: true,
                    columnCount: tbl?.columnCount || 0,
                    mappedColumns: 0,
                    confidence: 'none',
                    score: 0,
                    rowCount: 0
                };
            });

            importableTables = [...matchedTables, ...unmatchedTables];
        } else {
            // Fallback: show all source tables as manual
            importableTables = dbInfo?.tables?.map(tbl => ({
                prairieTable: tbl.name,
                sourceTable: tbl.name,
                found: true,
                columnCount: tbl.columnCount,
                mappedColumns: 0,
                confidence: 'manual',
                rowCount: 0
            })) || [];
        }

        const foundTables = importableTables.filter(t => t.found);
        const selectedCount = Object.values(selectedTables).filter(Boolean).length;

        const handleSelectAll = () => {
            const newSelection = { ...selectedTables };
            foundTables.forEach(t => { newSelection[t.prairieTable] = true; });
            setSelectedTables(newSelection);
        };

        const handleDeselectAll = () => {
            const newSelection = { ...selectedTables };
            importableTables.forEach(t => { newSelection[t.prairieTable] = false; });
            setSelectedTables(newSelection);
        };

        return (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                {renderWizardHeader()}

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 320px', gap: '15px' }}>
                    <div style={{ background: 'rgba(0,0,0,0.2)', padding: '20px', borderRadius: '12px', border: '1px solid var(--glass-border)' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '15px' }}>
                            <h4 style={{ margin: 0, color: 'var(--primary)', fontSize: '0.95rem' }}>
                                {t('data.bridge.selectTablesToImport')}
                            </h4>
                            <div style={{ display: 'flex', gap: '6px', alignItems: 'center' }}>
                                <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>
                                    {selectedCount} of {foundTables.length} selected
                                </span>
                                <button
                                    onClick={handleSelectAll}
                                    style={{
                                        display: 'flex', alignItems: 'center', gap: '4px',
                                        padding: '4px 10px', borderRadius: '6px', fontSize: '0.72rem', fontWeight: 600,
                                        border: '1px solid rgba(16,185,129,0.3)', background: 'rgba(16,185,129,0.08)',
                                        color: '#10b981', cursor: 'pointer', transition: 'all 0.2s'
                                    }}
                                    title={t('dataBridge.selectAllAvailableTablesForTip')}
                                >
                                    <CheckSquare size={12} /> Select All
                                </button>
                                <button
                                    onClick={handleDeselectAll}
                                    style={{
                                        display: 'flex', alignItems: 'center', gap: '4px',
                                        padding: '4px 10px', borderRadius: '6px', fontSize: '0.72rem', fontWeight: 600,
                                        border: '1px solid var(--glass-border)', background: 'transparent',
                                        color: 'var(--text-muted)', cursor: 'pointer', transition: 'all 0.2s'
                                    }}
                                    title={t('dataBridge.deselectAllTablesTip')}
                                >
                                    <Square size={12} /> Clear All
                                </button>
                            </div>
                        </div>

                        <div style={{ maxHeight: '400px', overflowY: 'auto' }} className="scroll-area">
                        {importableTables.map(table => (
                            <label
                                key={table.prairieTable}
                                style={{
                                    display: 'flex', alignItems: 'center', gap: '12px', 
                                    padding: '12px 15px', borderRadius: '8px', cursor: table.found ? 'pointer' : 'not-allowed',
                                    background: selectedTables[table.prairieTable] 
                                        ? table.confidence === 'high' ? 'rgba(16, 185, 129, 0.06)' : 'rgba(99, 102, 241, 0.08)' 
                                        : 'transparent',
                                    border: selectedTables[table.prairieTable] 
                                        ? table.confidence === 'high' ? '1px solid rgba(16, 185, 129, 0.25)' : '1px solid rgba(99, 102, 241, 0.2)' 
                                        : '1px solid transparent',
                                    opacity: table.found ? 1 : 0.4, marginBottom: '4px', transition: 'all 0.2s'
                                }}
                            >
                                <input
                                    type="checkbox"
                                    checked={!!selectedTables[table.prairieTable]}
                                    disabled={!table.found}
                                    onChange={e => setSelectedTables({ ...selectedTables, [table.prairieTable]: e.target.checked })}
                                    style={{ width: '18px', height: '18px', accentColor: table.confidence === 'high' ? '#10b981' : 'var(--primary)' }}
                                    title={`Include ${table.prairieTable} in the import`}
                                />
                                <div style={{ flex: 1 }}>
                                    <div style={{ fontWeight: 600, fontSize: '0.9rem', display: 'flex', alignItems: 'center', gap: '6px' }}>
                                        {table.prairieTable}
                                        {table.targetTable && table.targetTable !== table.sourceTable && (
                                            <span style={{ fontSize: '0.7rem', color: '#10b981', fontWeight: 400 }}>→ {table.targetTable}</span>
                                        )}
                                    </div>
                                    <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                                        {table.mappedColumns > 0 ? `${table.mappedColumns}/${table.columnCount} columns matched` : `${table.columnCount} columns`}
                                        {table.rowCount > 0 && ` • ${table.rowCount.toLocaleString()} rows`}
                                    </div>
                                </div>
                                <div style={{ display: 'flex', gap: '4px' }}>
                                    {table.found ? (
                                        table.confidence === 'high' ? (
                                            <span className="badge badge-green" style={{ fontSize: '0.68rem' }}>✓ Auto-matched</span>
                                        ) : table.confidence === 'medium' ? (
                                            <span className="badge badge-yellow" style={{ fontSize: '0.68rem' }}>~ Likely match</span>
                                        ) : table.confidence === 'low' ? (
                                            <span className="badge badge-yellow" style={{ fontSize: '0.68rem' }}>? Low match</span>
                                        ) : connectorProfile ? (
                                            <span className="badge badge-green" style={{ fontSize: '0.68rem' }}>{table.mappedColumns} mapped</span>
                                        ) : table.confidence === 'none' ? (
                                            <span className="badge badge-gray" style={{ fontSize: '0.68rem' }}>No match</span>
                                        ) : (
                                            <span className="badge badge-yellow" style={{ fontSize: '0.68rem' }}>Manual</span>
                                        )
                                    ) : (
                                        <span className="badge badge-red">{t('data.bridge.notFound')}</span>
                                    )}
                                </div>
                            </label>
                        ))}
                        </div>
                    </div>

                    {/* Column mapping preview */}
                    <div style={{ background: 'rgba(0,0,0,0.15)', padding: '20px', borderRadius: '12px', border: '1px solid var(--glass-border)', display: 'flex', flexDirection: 'column', gap: '15px' }}>
                        <h4 style={{ margin: 0, color: 'var(--primary)', fontSize: '0.95rem' }}>{t('data.bridge.columnConfidence')}</h4>
                        
                        {connectorProfile ? (
                            <>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.82rem' }}>
                                    <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#10b981' }} />
                                    <span style={{ color: '#10b981' }}>{t('data.bridge.confirmedMatchAutomapped')}</span>
                                </div>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.82rem' }}>
                                    <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#f59e0b' }} />
                                    <span style={{ color: '#f59e0b' }}>{t('data.bridge.needsReviewFuzzyMatch')}</span>
                                </div>

                                <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '10px' }}>
                                    The {connectorProfile.name} connector profile has pre-mapped column names from previous successful migrations.
                                </div>
                            </>
                        ) : autoMatchResults ? (
                            <>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.82rem' }}>
                                    <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#10b981' }} />
                                    <span style={{ color: '#10b981' }}>
                                        High Confidence ({autoMatchResults.matches.filter(m => m.confidence === 'high').length})
                                    </span>
                                </div>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.82rem' }}>
                                    <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#f59e0b' }} />
                                    <span style={{ color: '#f59e0b' }}>
                                        Medium / Low ({autoMatchResults.matches.filter(m => m.confidence !== 'high').length})
                                    </span>
                                </div>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.82rem' }}>
                                    <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#6b7280' }} />
                                    <span style={{ color: '#6b7280' }}>
                                        Unmatched ({autoMatchResults.unmatchedSource?.length || 0})
                                    </span>
                                </div>

                                <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '10px' }}>
                                    Schema auto-match compared {autoMatchResults.totalSourceTables} source tables against {autoMatchResults.totalTrierTables} Trier tables using name + column matching.
                                </div>
                            </>
                        ) : (
                            <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                                No connector profile loaded. Tables will be imported using direct column name matching.
                            </div>
                        )}

                        <div style={{ background: 'rgba(16, 185, 129, 0.05)', padding: '12px', borderRadius: '8px', border: '1px solid rgba(16, 185, 129, 0.2)', marginTop: 'auto' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '6px' }}>
                                <Shield size={14} color="#10b981" />
                                <span style={{ fontSize: '0.8rem', fontWeight: 600, color: '#10b981' }}>{t('data.bridge.plantIsolation')}</span>
                            </div>
                            <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', margin: 0, lineHeight: 1.4 }}>
                                {t('data.bridge.thisImportOnlyAffects')} <strong>{currentPlant?.label}</strong>. Other sites are physically isolated.
                            </p>
                        </div>
                    </div>
                </div>

                <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <button className="btn-secondary" onClick={handleBack} style={{ padding: '8px 16px', fontSize: '0.85rem' }} title={t('dataBridge.goBackToThePreviousTip')}>
                        <ArrowLeft size={14} /> {t('data.bridge.back')}
                    </button>
                    <button                         className="btn-primary" 
                        onClick={() => setWizardStep('confirm')} 
                        disabled={Object.values(selectedTables).filter(Boolean).length === 0}
                        style={{ padding: '8px 20px', fontSize: '0.85rem', display: 'flex', alignItems: 'center', gap: '6px' }}
                        title={t('dataBridge.reviewAndConfirmConfigurationBeforeTip')}
                    >
                        {t('data.bridge.reviewConfirm')} <ArrowRight size={14} />
                    </button>
                </div>
            </div>
        );
    };

    // ═══════════════════════════════════════════════════════════════════════════
    // RENDER: CONFIRMATION (Step 5)
    // ═══════════════════════════════════════════════════════════════════════════

    const renderConfirmation = () => {
        const tablesToImport = Object.keys(selectedTables).filter(k => selectedTables[k]);
        const tablesToDefer = connectorProfile ?
            Object.keys(connectorProfile.tables).filter(k => !selectedTables[k]) : [];

        return (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                {renderWizardHeader()}

                <div style={{ background: 'rgba(0,0,0,0.2)', padding: '20px', borderRadius: '12px', border: '1px solid var(--glass-border)' }}>
                    <h4 style={{ margin: '0 0 15px 0', color: 'var(--primary)' }}>{t('data.bridge.importSummary')}</h4>

                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px', marginBottom: '20px' }}>
                        <div className="panel-box">
                            <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{t('data.bridge.source')}</div>
                            <div style={{ fontWeight: 600 }}>{activeSource?.label} — {dbInfo?.file || t('data.bridge.connected')}</div>
                        </div>
                        <div className="panel-box">
                            <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{t('data.bridge.target')}</div>
                            <div style={{ fontWeight: 600 }}>{currentPlant?.label}</div>
                        </div>
                    </div>

                    <div style={{ marginBottom: '15px' }}>
                        <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '8px' }}>{t('data.bridge.tablesToImport')}</div>
                        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
                            {tablesToImport.map(tbl => <span key={tbl} className="badge badge-green">{tbl}</span>)}
                        </div>
                    </div>

                    {tablesToDefer.length > 0 && (
                        <div style={{ marginBottom: '15px' }}>
                            <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '8px' }}>{t('data.bridge.deferredCanImportLater')}</div>
                            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
                                {tablesToDefer.map(tbl => <span key={tbl} className="badge badge-yellow">{tbl}</span>)}
                            </div>
                        </div>
                    )}
                </div>

                <div style={{ background: 'rgba(239, 68, 68, 0.1)', padding: '15px', borderRadius: '8px', border: '1px solid rgba(239, 68, 68, 0.4)' }}>
                    <h4 style={{ margin: '0 0 10px 0', color: '#f87171', display: 'flex', alignItems: 'center', gap: '5px', fontSize: '1rem' }}>
                        <AlertTriangle size={18} /> {t('data.bridge.confirmImportExecution')}
                    </h4>
                    <p style={{ fontSize: '0.85rem', marginBottom: '10px', color: 'var(--text-muted)' }}>
                        {t('data.bridge.aSafetySnapshotWill')}
                    </p>
                    <input
                        type="text"
                        placeholder={`Type "TrierCMMS" to confirm`}
                        value={confirmPlant}
                        onChange={e => setConfirmPlant(e.target.value)}
                        style={{ width: '100%', padding: '10px', borderRadius: '6px', border: '1px solid var(--glass-border)', background: 'var(--bg-dark)', color: '#fff' }}
                        title={t('dataBridge.typeTriercmmsToConfirmTheTip')}
                    />
                </div>

                <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <button className="btn-secondary" onClick={handleBack} style={{ padding: '8px 16px', fontSize: '0.85rem' }} title={t('dataBridge.goBackToThePreviousTip')}>
                        <ArrowLeft size={14} /> {t('data.bridge.back')}
                    </button>
                    <button
                        className="btn-danger"
                        disabled={confirmPlant !== 'TrierCMMS'}
                        onClick={executeImport}
                        title={t('dataBridge.executeTheDataImportATip')}
                    >
                        {t('data.bridge.executeImport')} <ArrowRight size={14} />
                    </button>
                </div>
            </div>
        );
    };

    // ═══════════════════════════════════════════════════════════════════════════
    // RENDER: WIZARD HEADER (shared)
    // ═══════════════════════════════════════════════════════════════════════════

    const renderWizardHeader = () => {
        const steps = ['connect', 'browse', 'scope', 'confirm'];
        const stepLabels = ['Connect', 'Browse', 'Configure', 'Import'];
        const currentIdx = steps.indexOf(wizardStep);

        return (
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '5px' }}>
                <div style={{
                    width: '32px', height: '32px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center',
                    background: `${activeSource?.color}22`, border: `1px solid ${activeSource?.color}44`
                }}>
                    {activeSource && React.createElement(activeSource.icon, { size: 16, color: activeSource.color })}
                </div>
                <div>
                    <h3 style={{ margin: 0, fontSize: '1.1rem' }}>{activeSource?.label} Import</h3>
                    <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{activeSource?.desc}</div>
                </div>

                <div style={{ marginLeft: 'auto', display: 'flex', gap: '6px', alignItems: 'center' }}>
                    {stepLabels.map((label, idx) => (
                        <React.Fragment key={label}>
                            <span style={{ 
                                padding: '3px 10px', borderRadius: '12px', fontSize: '0.72rem', fontWeight: 600,
                                background: idx === currentIdx ? 'var(--primary)' : idx < currentIdx ? 'rgba(16,185,129,0.15)' : 'rgba(255,255,255,0.05)',
                                color: idx === currentIdx ? '#fff' : idx < currentIdx ? '#10b981' : 'var(--text-muted)'
                            }}>
                                {label}
                            </span>
                            {idx < stepLabels.length - 1 && <ChevronRight size={12} color="var(--text-muted)" />}
                        </React.Fragment>
                    ))}
                </div>
            </div>
        );
    };

    // ═══════════════════════════════════════════════════════════════════════════
    // MAIN RENDER
    // ═══════════════════════════════════════════════════════════════════════════

    return (
        <div className="glass-card" style={{ padding: '25px', display: 'flex', flexDirection: 'column', gap: '15px', background: 'rgba(255,255,255,0.03)' }}>
            {error && (
                <div style={{ background: 'rgba(239, 68, 68, 0.1)', color: '#f87171', padding: '10px 15px', borderRadius: '8px', border: '1px solid rgba(239, 68, 68, 0.5)', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.85rem' }}>
                    <AlertTriangle size={16} /> {error}
                    <button onClick={() => setError(null)} style={{ marginLeft: 'auto', background: 'none', border: 'none', cursor: 'pointer', color: '#f87171', padding: '4px' }} title={t('dataBridge.dismissThisErrorMessageTip')}>
                        <XCircle size={16} />
                    </button>
                </div>
            )}

            {wizardStep === 'select' && renderSourceSelector()}
            {wizardStep === 'connect' && renderConnectionStep()}
            {wizardStep === 'browse' && renderTableBrowser()}
            {wizardStep === 'scope' && renderScopeSelector()}
            {wizardStep === 'confirm' && renderConfirmation()}

            {/* ── IMPORTING IN PROGRESS ── */}
            {wizardStep === 'importing' && (
                <div style={{ textAlign: 'center', padding: '60px 20px' }}>
                    <Loader size={48} className="spinning" style={{ color: 'var(--primary)', marginBottom: '20px' }} />
                    <h3 style={{ marginBottom: '10px' }}>{t('data.bridge.importingData')}</h3>
                    <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', maxWidth: '400px', margin: '0 auto' }}>
                        Creating safety snapshot and importing records into {currentPlant?.label}.
                        This may take a moment for large datasets.
                    </p>
                    <div style={{ marginTop: '20px', display: 'flex', justifyContent: 'center', gap: '8px' }}>
                        {Object.keys(selectedTables).filter(k => selectedTables[k]).map(tbl => (
                            <span key={tbl} className="badge badge-purple" style={{ animation: 'pulse 2s infinite' }}>{tbl}</span>
                        ))}
                    </div>
                </div>
            )}

            {/* ── IMPORT RESULTS REPORT ── */}
            {wizardStep === 'report' && importResults && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                        <CheckCircle size={32} color="#10b981" />
                        <div>
                            <h3 style={{ margin: 0 }}>{t('data.bridge.importComplete')}</h3>
                            <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Session ID: {importResults.importId}</div>
                        </div>
                        <div className="badge badge-green" style={{ marginLeft: 'auto' }}>{importResults.plant}</div>
                    </div>

                    {/* Stats grid */}
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: '10px' }}>
                        {[
                            { label: 'Total Records', val: importResults.stats.total, color: '#fff' },
                            { label: t('data.bridge.inserted'), val: importResults.stats.inserted, color: '#10b981' },
                            { label: t('data.bridge.updated'), val: importResults.stats.updated, color: '#6366f1' },
                            { label: 'Auto-Healed', val: importResults.stats.autoHealed, color: '#f59e0b' },
                            { label: t('data.bridge.skipped'), val: importResults.stats.skipped, color: 'var(--text-muted)' }
                        ].map(s => (
                            <div key={s.label} style={{ background: 'rgba(0,0,0,0.2)', padding: '15px', borderRadius: '10px', textAlign: 'center', border: '1px solid var(--glass-border)' }}>
                                <div style={{ fontSize: '1.6rem', fontWeight: 700, color: s.color, fontFamily: "'Outfit', sans-serif" }}>{s.val}</div>
                                <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{s.label}</div>
                            </div>
                        ))}
                    </div>

                    {/* Per-table breakdown */}
                    <div style={{ background: 'rgba(0,0,0,0.15)', padding: '20px', borderRadius: '12px', border: '1px solid var(--glass-border)' }}>
                        <h4 style={{ margin: '0 0 12px 0', color: 'var(--primary)', fontSize: '0.95rem' }}>{t('data.bridge.pertableResults')}</h4>
                        <div style={{ overflowX: 'auto' }}>
                            <table className="data-table" style={{ fontSize: '0.82rem', width: '100%' }}>
                                <thead>
                                    <tr>
                                        <th style={{ textAlign: 'left', padding: '8px 12px' }}>{t('data.bridge.table')}</th>
                                        <th style={{ textAlign: 'center', padding: '8px' }}>{t('data.bridge.inserted')}</th>
                                        <th style={{ textAlign: 'center', padding: '8px' }}>{t('data.bridge.updated')}</th>
                                        <th style={{ textAlign: 'center', padding: '8px' }}>{t('data.bridge.healed')}</th>
                                        <th style={{ textAlign: 'center', padding: '8px' }}>{t('data.bridge.skipped')}</th>
                                        <th style={{ textAlign: 'left', padding: '8px' }}>{t('data.bridge.status')}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {Object.entries(importResults.tableResults).map(([table, r]) => (
                                        <tr key={table}>
                                            <td style={{ padding: '8px 12px', fontWeight: 600 }}>{table}</td>
                                            <td style={{ textAlign: 'center', padding: '8px', color: '#10b981' }}>{r.inserted}</td>
                                            <td style={{ textAlign: 'center', padding: '8px', color: '#6366f1' }}>{r.updated}</td>
                                            <td style={{ textAlign: 'center', padding: '8px', color: '#f59e0b' }}>{r.autoHealed}</td>
                                            <td style={{ textAlign: 'center', padding: '8px', color: 'var(--text-muted)' }}>{r.skipped}</td>
                                            <td style={{ padding: '8px' }}>
                                                {r.errors.length === 0 
                                                    ? <span className="badge badge-green" style={{ fontSize: '0.7rem' }}>✓ OK</span>
                                                    : <span className="badge badge-red" style={{ fontSize: '0.7rem' }}>{r.errors.length} error(s)</span>
                                                }
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </div>

                    {/* Snapshot info */}
                    <div style={{ background: 'rgba(16, 185, 129, 0.05)', padding: '12px 15px', borderRadius: '8px', border: '1px solid rgba(16, 185, 129, 0.2)', display: 'flex', alignItems: 'center', gap: '10px' }}>
                        <Shield size={16} color="#10b981" />
                        <div style={{ fontSize: '0.8rem' }}>
                            <strong style={{ color: '#10b981' }}>{t('data.bridge.snapshotSaved')}</strong>
                            <span style={{ color: 'var(--text-muted)', marginLeft: '6px' }}>{importResults.snapshotFile}</span>
                        </div>
                    </div>

                    <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px' }}>
                        <button className="btn-secondary" onClick={() => {
                            setWizardStep('select');
                            setActiveSource(null);
                            setDbInfo(null);
                            setSelectedFile(null);
                            setImportResults(null);
                            setConfirmPlant('');
                            setSelectedTables({});
                        }} style={{ padding: '8px 16px', fontSize: '0.85rem' }} title={t('dataBridge.startANewImportSessionTip')}>
                            {t('data.bridge.newImport')}
                        </button>
                        {onComplete && (
                            <button className="btn-primary btn-sm" onClick={onComplete} title={t('dataBridge.finishAndCloseTheImportTip')}>
                                {t('data.bridge.done')}
                            </button>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}
