// Copyright © 2026 Trier OS. All Rights Reserved.

/**
 * Gatekeeper Intent Schema
 * 
 * Defines the shape of the data passed from Trier OS routes to the Gatekeeper.
 */

module.exports = {
    /**
     * @typedef {Object} Intent
     * @property {string} requestId - UUID v4, generated by caller (S-12 collision-resistant)
     * @property {string} userId - req.user.UserID (from JWT)
     * @property {string} username - req.user.Username (capital U)
     * @property {string} plantId - validated against SAFE_PLANT_ID
     * @property {string} actionClass - READ_ONLY | ADVISORY | NON_CRITICAL | SAFETY_CRITICAL
     * @property {string} actionType - semantic label e.g. 'LOTO_ACTIVATE', 'MOC_APPROVE', 'SETPOINT_WRITE'
     * @property {string} targetType - ASSET | WORK_ORDER | LOTO_PERMIT | MOC_RECORD | FIELD_DEVICE
     * @property {string} targetId - ID of the specific entity being acted on
     * @property {object} payload - the proposed write (before snapshot)
     * @property {string} ipAddress - req.ip
     */
};
